#include <kdialog.h>
#include <klocale.h>
/****************************************************************************
** Form implementation generated from reading ui file './gemdDlg.ui'
**
** Created: Tue Feb 13 12:49:39 2007
**      by: The User Interface Compiler ($Id: qt/main.cpp   3.3.6   edited Aug 31 2005 $)
**
** WARNING! All changes made in this file will be lost!
****************************************************************************/

#include "gemdDlg.h"

#include <qvariant.h>
#include <qtextedit.h>
#include <qlabel.h>
#include <qlineedit.h>
#include <qcheckbox.h>
#include <qpushbutton.h>
#include <qlistbox.h>
#include <qlayout.h>
#include <qtooltip.h>
#include <qwhatsthis.h>
#include <qimage.h>
#include <qpixmap.h>

static const char* const img0_gemdDlg[] = { 
"64 64 64 1",
"9 c #000000",
"# c #006b00",
"h c #007300",
"q c #007b00",
"g c #008000",
"Q c #008c00",
"e c #009c00",
"d c #00ad00",
"i c #107b08",
"r c #188c08",
"j c #218410",
"s c #219410",
"k c #299410",
"t c #299c10",
"u c #31a518",
"l c #39a518",
"v c #39ad18",
"m c #42ad21",
"w c #42b521",
"x c #4abd21",
"n c #52b529",
"o c #5abd29",
"p c #63c629",
"c c #63ce31",
"b c #7bce52",
"I c #a0a0a4",
"H c #a5a5a5",
"G c #a5a5ad",
"Z c #a5adad",
"F c #adadad",
"E c #adadb5",
"0 c #b5b5b5",
"D c #b5b5bd",
"C c #b5b5c6",
"T c #b5bdbd",
"S c #b5bdc6",
"J c #bdbdbd",
"B c #bdbdc6",
"R c #bdbdce",
"A c #bdc6ce",
"Y c #bdc6d6",
"a c #c0c0c0",
"K c #c6c6c6",
"z c #c6c6d6",
"y c #c6c6de",
"6 c #c6cece",
"1 c #cecece",
"U c #ceced6",
"L c #ced6d6",
"V c #d6d6de",
"M c #d6dede",
". c #d9d9d9",
"7 c #dedede",
"W c #dedee7",
"N c #dee7e7",
"2 c #e7e7e7",
"O c #e7e7ef",
"3 c #e7efef",
"P c #efefef",
"X c #efeff7",
"4 c #eff7f7",
"8 c #f7f7f7",
"5 c #f7f7ff",
"f c #ffffff",
"................................................................",
"................................................................",
"....#######aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabccc######.....",
"...#dddd###aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabccc#######....",
"...#ddee###ffffffffffffffffffffffffffffffffffffffffccgg#####....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffccee##h##....",
"...#ddeeh##ffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffccee##h##....",
"...#ddeeh##ffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffccee##h##....",
"...#ddeeh##ffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffccee##h##....",
"...#ddeeh##ffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffccee##h##....",
"...#ddeeh##ffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffccee##h##....",
"...#ddeeh##ffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffccee##h##....",
"...#ddeeh##ffffffffffffffffffffffffffffffffffffffffcceehhh##....",
"...#ddeeh####ijklmnopcccccccccccccccccccccccccccccccceeeeg##....",
"...#ddeeh####ijklmnopcccccccccccccccccccccccccccccccceeeeg##....",
"...#ddeeqhhhhirstuvwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxeeeeg##....",
"...#ddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeg##....",
"...#ddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeg##....",
"...#ddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeg##....",
"...#ddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeg##....",
"...#ddeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeg##....",
"...#ddeeeeeeeeeeg##yyzABCDEEFGHHIIIFJKLMNOPP########qQeeeg##....",
"...#ddeeeeeeeeeeg##zzARSDDEFGHHIIIFTKUVWOPXX########qQeeeg##....",
"...#ddeeeeeeeeeeg##YYARSDDEFGHIIIZ0K1VW23X44########qQeeeg##....",
"...#ddeeeeeeeeeeg##RRR########IIH0a1.W23X455########qQeeeg##....",
"...#ddeeeeeeeeeeg##BBB########IH0a6.723X4855########qQeeeg##....",
"...#ddeee999eeeeg##99C####99##HFJ99999X99555########qQeeeg##....",
"...#ddeee999eeeeg##99D####99##FJ99MNOPX99555########qQeeeg##....",
"...#ddee99e99eee99999D#99999##D9999O99499589999###9999eeeg##....",
"...#ddee99e99ee99##99E99##99##a1992399599599##99#99#q99eeg##....",
"...#ddee99e99ee99##99E99##99##6.993X995994999999#9999Qeeeg##....",
"...#dde9999999e99##99F99##99##L799X499599X99#######9999eeg##....",
"...#dde99eee99e99##99G99##99##MN994899599P99##99#99#q99eeg##....",
"...#dde99eee99ee99999H#99999##WO994599899O29999###9999eeeg##....",
"...#ddeeeeeeeeeeg##HHH########23X455584P3222########qQeeeg##....",
"...#ddeeeeeeeeeeg##III########3X485554X322WW########qQeeeg##....",
"...#ddeeeeeeeeeeg##III########X485554XPO2W77########qQeeeg##....",
"...#ddeeeeeeeeeeg##IIITKUVWOPX485554XPO2N777########qQeeeg##....",
"...#ddeeeeeeeeeeg##IIFTKUVWOPX45558XPO2N77..########qQeeeg##....",
"...#ddeeeeeeeeeeg##GG0K1VW23X455584P32277...########qQeeeg##....",
"...#ddggggggggggh##000DJJaaaKKKKKKKaaaaaJJJJ########hqgggh##....",
"...#dd#############0000000000000000000000000################....",
"....###############0000000000000000000000000###############.....",
"................................................................",
"................................................................"};

static const char* const img1_gemdDlg[] = { 
"64 64 144 2",
"a# c #004200",
"al c #004a00",
"am c #005200",
"#m c #005a08",
".u c #006308",
".t c #006b08",
".a c #007308",
".# c #007b08",
".b c #008410",
"ac c #008c10",
".P c #008c18",
".x c #008c21",
"#F c #009418",
".2 c #009421",
".d c #009429",
"#. c #009c21",
"#b c #009c29",
".c c #009c31",
".D c #00a529",
"#r c #00a531",
".r c #00a539",
"af c #00a542",
".9 c #00ad31",
"#B c #00ad39",
".C c #00ad42",
"ak c #00b539",
"#h c #00b542",
"#v c #00b54a",
"ai c #00bd4a",
"#J c #08a542",
"ad c #08ad42",
".8 c #08bd42",
"#n c #08bd4a",
"#A c #08bd52",
"ab c #10ad4a",
".B c #10b54a",
"#S c #10bd4a",
"aj c #10c64a",
"#u c #10c652",
".A c #18b54a",
".s c #18c64a",
"#9 c #18c652",
"#q c #18c65a",
"ag c #18ce52",
"#c c #21ad52",
".z c #21b552",
"#6 c #21c652",
"#a c #21c65a",
"ae c #21ce5a",
".y c #29b55a",
"#7 c #29bd52",
"#5 c #29c652",
"#f c #29ce5a",
"aa c #29ce63",
"a. c #29d65a",
"#3 c #29d663",
"#Z c #31c65a",
"#X c #31ce5a",
"#e c #31ce63",
"#0 c #31d663",
".e c #39b563",
"#U c #39ce5a",
"## c #39d663",
"#t c #42bd6b",
"#V c #42ce5a",
"#Q c #42d663",
".7 c #42d66b",
".O c #42de6b",
"#R c #4ace63",
"an c #4ad673",
".N c #4ade6b",
"#K c #52d66b",
".5 c #52de6b",
"#4 c #52de73",
".1 c #52e773",
".f c #5abd73",
"#L c #5ace6b",
"#2 c #5ade7b",
".4 c #5ae773",
"#G c #63d673",
".M c #63de7b",
".w c #63e773",
"#1 c #63e77b",
"#E c #6bd67b",
".3 c #6be77b",
"#d c #73c684",
"#C c #73d684",
"#Y c #73e77b",
".L c #73e784",
".0 c #73ef7b",
".q c #73ef84",
"#W c #7bef84",
"#l c #84ce8c",
"#D c #84d684",
"#x c #84d68c",
"#O c #84de94",
"#N c #84e78c",
".R c #84ef84",
".Z c #84ef8c",
".i c #8cce94",
".K c #8ce794",
".v c #8cef8c",
"#y c #94d68c",
".E c #94d694",
".Y c #94ef94",
".X c #9cef94",
"#M c #9cef9c",
"#k c #a5d69c",
"#I c #a5e7a5",
".n c #a5ef9c",
"#o c #add69c",
"#P c #add6a5",
"#8 c #ade7a5",
"#H c #adefa5",
".W c #adf79c",
"#j c #b5dea5",
".S c #b5efa5",
".o c #bde7ad",
".J c #bdefad",
".m c #bdf7ad",
"#s c #c6efad",
".g c #cedeb5",
"#p c #cee7b5",
"ah c #cee7bd",
".p c #cef7b5",
".I c #d6efbd",
".V c #d6f7b5",
".U c #d6f7bd",
"Qt c #d9d9d9",
".l c #def7bd",
".H c #e7efc6",
".h c #efe7c6",
"#i c #efefc6",
"#z c #efefce",
"#w c #eff7c6",
"#g c #f7efce",
".T c #f7f7ce",
".6 c #ffefd6",
".k c #fff7d6",
".j c #fff7de",
".Q c #fff7e7",
".G c #fff7ef",
"#T c #ffffef",
".F c #fffff7",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQt.#.a.a.a.#.a.a.a.#.#.#.#.#.#.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#.b.c.d.#.aQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQt.#.#.b.e.f.f.f.g.g.g.hQtQtQtQtQtQt.c.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQt.#.#.#.iQtQtQt.j.j.j.k.l.l.l.m.n.n.n.o.#.aQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQt.#.#.eQt.p.q.q.q.q.q.q.q.q.q.q.q.q.q.q.r.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.a.a.a.a.a.aQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"Qt.#.#.dQt.j.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.s.#.t.u.a.a.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.#.#.hQt.v.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.w.#.#.#.#.#.#.#.#.#.#.#.x.c.c.c.c.c.c.y.z.A.B.C.C.D.#.tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.#.fQt.l.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.E.g.g.g.gQtQtQtQtQtQtQt.F.G.j.k.H.I.J.n.K.L.M.N.O.P.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.b.Q.F.R.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.S.j.j.j.j.T.U.U.U.U.U.V.W.X.Y.Y.v.Z.R.q.q.q.q.0.1.2.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.cQt.I.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.2.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.cQt.L.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.2.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.c.k.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.2.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.c.k.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.2.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.c.k.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.2.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.c.k.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.2.#QtQt.a.a.a.#.#.#.#.#.#.#.uQtQt",
".#.c.6.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.8.9#..2.2.2.2.#.#.#.#.#.#.#.#.#.#.#.c.c.c.d.#.aQtQt",
".#.c.6#################################################################a#b.b.#.#.#.#.#.d.c.c#c.f.f#d.g.g.hQtQtQtQtQtQt.Q.d.#QtQt",
".#.c.6#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#f.D.#.#.b.e.gQtQtQtQtQtQt.F.Q.Q.F.G.G.G.Q.Q.Q.j.j.k.k.b.#QtQt",
".#.c#g#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#h.b.#.x.iQt.F.Q.k.T.T#i.l.l.l#j#k.j.j.j.j.j.k.k.k.k.k#l.##mQtQt",
".#.c#g#f#f#f#f#f#f#f#f#f#f#f#f#f#f#f#f#f#f#f#f#f#f#f#f#f#f#f#a#..#.b#dQt.F.k.l.l.l.l.l.l.l.l.l#j#k.j.j.k.k.k.k.k.k.k.k.r.#QtQtQt",
".#.c#g#a#a#a#a#a#a#a#a#a#a#a#a#a#a#a#a#a#a#a#a#a#a#a#a#a#a#n.b.#.c.6.F.k.I.I.I.I.I.I.I.I.I.I.I#k#o.k.k.k.k.k.k.k.k.k#p.#.aQtQtQt",
".#.##g#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#r.#.b#dQt.Q.p#s#s#s#s#s#s#s#s#s#s#s#s.E#k.T.T#g#i#i#i#i#i#i#t.#QtQtQtQt",
".#.##g#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#v.2.#.d.h.F#w.J.J.J.J.J.J.J.J.J.J.J.J.J.J#x#y.l.l.l.l.l.l.l.I.I.b.#QtQtQtQt",
".#.##z#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#h#B.C.D.P.#.##c.Q.Q.J.n.n.n.n.n.n.n.n.n.n.n.n.n.n.n#C#D#s#s#s#s#s#s#s.J#E.#QtQtQtQtQt",
".#.##p#n#n#n#n#n#n#n#n#n#n.C#B#b#b#.#F.b.#.#.#.#.#.#.x.iQt.k.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y.Y#G#E.S.S.S.S#H#H#H#H.r.#QtQtQtQtQt",
".#.##I#v#v#v#v#v#v#v#v#v.P.#.#.#.#.#.#.x.c#J.f.f.i#gQt.G.J.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z#K#L#M.X.X.X.X.X.Y#N.#.aQtQtQtQtQt",
".#.##O#v#v#v#v#v#v#v#h.P.##b.f#P.g.6QtQtQtQt.k.k.k.U.X.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L#Q#R.v#N#N#N#N#N#N#S.#QtQtQtQtQtQt",
".#.#.M#v#v#v#v#v#v#v.P.##c#T.Q.T.p#s.X.X.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.3#U#V#W.L.L.L.L.L.L.b.#QtQtQtQtQtQt",
".#.#.7#v#v#v#v#v#v#B.#.d.G#w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w#X#U#Y.3.3.3.3.3#Z.#QtQtQtQtQtQtQt",
".#.##0#v#v#v#v#v#v.2.#.h.k.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4#f#U#1#1.M.M.M.M.D.#QtQtQtQtQtQtQt",
".#.##0#h#h#h#h#h.C.##cQt.L.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4#f#Z.M.M#2#2#2#K.#.aQtQtQtQtQtQtQt",
".#.##3#h#h#h#h#h#r.#.6.H#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#4#5#Z#4#4#4#4#4.8.#QtQtQtQtQtQtQtQt",
".#.##0#h#h#h#h#h.2.dQt.3.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.N#6#Z.5.5.N.N.N.b.#QtQtQtQtQtQtQtQt",
".#.##0.C.C.C.C.C.##d.j.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N#Q#6#7.N.N.N.N#6.#.uQtQtQtQtQtQtQtQt",
".#.##0.C.C.C.C#r.#.6#8.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O###9#7.7.7.7.7#b.#QtQtQtQtQtQtQtQtQt",
".#.#a..C.C.C.C.P#JQt#2.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7#0#S.z#######e.b.#QtQtQtQtQtQtQtQtQt",
".#.#a..C.C.C#B.#.i.j#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#Q#e#S.z######.C.#QtQtQtQtQtQtQtQtQtQt",
".#.##f.C.C.C.D.#.Q#I#########################################################################f#n.A#e#e#e.P.#QtQtQtQtQtQtQtQtQtQt",
".#.##f.C.C.C.P#JQt#4a#a#a#a#################################################################a#a#a#a#a##S.#.uQta#a#QtQtQtQtQtQtQt",
".#.##f#B#B#B.#.i.Ha#a#aaaaa#a#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa#a#abaaa#a#.#QtQta#a#QtQtQtQtQtQtQt",
".#.##f#B#B.D.#.Qa#a#aaaaaaaaa#a#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa#a#ab#f#fa#a#QtQtQtQtQtQtQtQtQtQtQt",
".#.####B#Bac#cQta#a##f#f#f#fa#a##f#fa#a##fa#a##f#f#f#fa#a#a#a##f#f#fa#a##fa#a##f#f#f#f#f#f#fa#a#ad#a#Ba#a#QtQta#a#QtQta#a#a#a#Qt",
".#.#.O#B#r.##P.Ha#a#aeaeaeaea#a#aeaea#a#a#aea#a#aeaea#a#aeaea#a#aeaea#a#a#aea#a#aeaeaeaeaeaea#a#af#a.Pa#a#QtQta#a#QtQta#a#QtQtQt",
".#.#.O#B#b.bQt#Oa#a##q#q#q#qa#a##q#qa#a##q#qa#a##q#qa#a##q#qa#a##q#qa#a##q#qa#a##q#q#q#q#q#qa#a#af#n.#a#a#QtQta#a#QtQta#a#QtQtQt",
".#.#.O#Bac#cQtaaa#a##q#q#q#qa#a##q#qa#a##q#qa#a##q#qa#a#a#a#a#a##q#qa#a##q#qa#a##q#q#q#q#u#na#a#af.x.#a#a#QtQta#a#QtQta#a#QtQtQt",
".a.#ag#B.##Pah#qa#a##q#q#q#qa#a##q#qa#a##q#qa#a##q#qa#a##q#q#q#q#q#qa#a##q#qa#a##nai#h.C.C#ra#a#.b.#.#a#a#QtQta#a#QtQta#a#QtQtQt",
".a.#aj#b.bQt#C#q#qa#a##q#qa#a##q#q#qa#a#a##qa#a##q#qa#a##q#qa#a##q#qa#a#ai#ha#a##r#b.2.P.#.#a#a#.#.ua#a#QtQtQta#a#QtQta#a#QtQtQt",
".a.#ajac.e.G#q#q#q#qa#a#a#a##q#q#q#qa#a##qa#a##q#q#q#qa#a#a#a#ai#h.Ca#a##r.2a#a#.#.#.#.#.a#ma#a#a#a#a#QtQtQtQta#a#QtQta#a#QtQtQt",
".a.#ak.#.hah#q#q#q#q#q#q#q#q#q#q#q#qa#a##q#q#q#q#u#Aai#h.C.C.C#r#..P.b.#.#.#.#.#.ualQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".a.#.2.xQt#C#q#q#q#q#q#q#q#q#q#q#q#qa#a##Aai#h.C.C.C#r#b.2.P.#.#.#.#.#.uamQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".a.#.b.e.G#q#q#q#q#q#q#q#q#q#9#uai#ha#a#.C#r#b.2.P.b.#.#.#.#.t#mQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".a.#.#.hah#q#q#q#q#9#uai#h#h.C.C#r#b.2.P.b.#.#.#.#.a.ualQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".a.#.xQtan#u#n#v#h.C.C#r#b.2.P.b.#.#.#.#.#.ualQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"Qt.#.b#k.C.C#r#b.2.P.b.#.#.#.#.#.ualQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"Qt.a.#.b.b.#.#.#.#.#.#.ualQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQt.u.#.#.u#malQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt"};

static const char* const img2_gemdDlg[] = { 
"64 64 156 2",
"#r c #002900",
"#s c #003900",
"ax c #005a08",
".K c #006308",
"#l c #006b00",
".J c #006b08",
"#F c #007300",
".l c #007308",
".k c #007b08",
".o c #008410",
"as c #008c10",
"#1 c #008c18",
"#y c #008c21",
"#7 c #009418",
"#U c #009421",
".q c #009429",
"#J c #009c21",
"aq c #009c29",
".p c #009c31",
"#0 c #00a529",
"#N c #00a531",
".H c #00a539",
"a. c #00a542",
"#Y c #00ad39",
"#Z c #00ad42",
"ay c #00b539",
"#E c #00b542",
"#T c #00b54a",
"#X c #00bd4a",
"#S c #00bd52",
"#B c #087b10",
"#L c #08bd4a",
".L c #105a00",
"#2 c #10b54a",
"af c #10bd4a",
"av c #10c64a",
"az c #10c652",
"#I c #18c652",
"#K c #18c65a",
"au c #18ce52",
".b c #213100",
"at c #21ce5a",
"ao c #21d65a",
"#t c #295200",
".I c #29c652",
"#A c #29ce5a",
"#z c #29ce63",
".a c #314200",
"al c #31c65a",
"aj c #31ce5a",
"#u c #31d663",
".# c #394a00",
"#h c #395200",
"#n c #396308",
".0 c #397b18",
".4 c #425a00",
"ak c #42bd52",
"ap c #42bd5a",
"#j c #42d663",
"#m c #42d66b",
"#V c #4a5a08",
".U c #4a6300",
".d c #4a6b00",
"## c #4a7300",
"#v c #4a8c31",
".t c #4abd6b",
"ae c #4ace63",
"aa c #4ace6b",
"an c #4ad66b",
"ar c #4ad673",
"#i c #4ade6b",
"#. c #526b00",
"ad c #527300",
".m c #527308",
".c c #527b10",
"#d c #52de73",
"#e c #5a8c29",
".u c #5abd73",
"am c #5ad663",
".P c #5ae773",
".5 c #637b00",
".T c #637b31",
"ag c #63de7b",
"#C c #6b8c00",
"#f c #6b9408",
"#c c #6b9410",
"ai c #6bbd52",
"#5 c #6bd67b",
".Z c #6be77b",
"#a c #73a510",
"aw c #73d684",
"#o c #7b9c10",
"#W c #7bad42",
"#w c #7bc684",
"#4 c #7bd684",
"a# c #7be77b",
".G c #7bef84",
".V c #84ad18",
"#H c #84ce8c",
"ab c #84e78c",
".X c #8ca521",
"#q c #8cc621",
"#P c #8cd68c",
"ac c #8cde94",
".O c #8cef8c",
".A c #94ce94",
"#3 c #94de73",
"#9 c #94de94",
".Q c #9cad31",
"#M c #9cad4a",
".E c #9cce31",
"#8 c #9cef94",
".M c #a5bd31",
".6 c #a5bd42",
".S c #a5de9c",
".D c #a5f79c",
".x c #adce4a",
".h c #adde42",
".e c #adef42",
"#O c #b5de94",
"#G c #b5dea5",
".7 c #bdc65a",
".C c #bdefad",
".8 c #c6ce63",
".9 c #c6e763",
"#b c #ced66b",
".v c #cedeb5",
"#6 c #d6efc6",
".F c #d6f7b5",
"Qt c #d9d9d9",
".g c #e7ef8c",
".B c #e7f7bd",
"#R c #e7f7c6",
"#p c #efd684",
".w c #efe7c6",
"#k c #efef94",
"#D c #efefce",
"#g c #f7ef9c",
"#Q c #f7f7ce",
".s c #f7ff94",
".1 c #ffefb5",
".N c #ffefc6",
".2 c #ffefce",
".R c #ffefd6",
".n c #fff7b5",
".f c #fff7c6",
".r c #fff7ce",
".y c #fff7d6",
".i c #fff7de",
"#x c #fff7e7",
".z c #ffffa5",
".3 c #ffffbd",
".Y c #ffffc6",
".j c #ffffde",
"ah c #ffffef",
".W c #fffff7",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.aQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.#.#.bQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.#.c.d.#.bQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.#.c.e.e.d.#.bQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.#.c.e.f.g.e.d.#.bQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.#.c.h.f.i.j.g.e.d.#.bQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQt.k.l.l.l.k.l.l.l.k.k.k.k.k.k.kQtQtQtQtQtQtQtQtQtQtQtQt.#.#.m.h.n.i.i.i.j.g.e.d.#.bQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQt.k.k.k.k.k.k.k.k.k.k.k.k.k.o.p.q.k.lQtQtQtQtQtQtQtQtQtQt.#.#.m.h.r.i.i.i.i.i.j.s.e.d.#.bQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQt.k.k.o.t.u.u.u.v.v.v.wQtQtQtQtQtQt.p.kQtQtQtQtQtQtQtQtQt.#.#.m.x.r.y.y.i.i.i.i.i.j.z.e.d.#.bQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQt.k.k.k.AQtQtQt.i.i.i.y.B.B.B.C.D.D.D.C.k.lQtQtQtQtQtQtQt.#.#.m.E.r.y.y.y.y.i.i.i.i.i.j.z.e.d.#.bQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQt.k.k.tQt.F.G.G.G.G.G.G.G.G.G.G.G.G.G.G.H.kQtQtQtQtQtQt.#.#.m.E.r.y.y.y.y.y.y.i.i.i.i.i.j.z.e.d.#.bQtQtQtQtQtQtQtQtQtQtQtQtQt",
"Qt.k.k.qQt.i.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.I.k.J.K.l.l.k.L.#.d.M.N.y.y.y.y.y.y.y.y.i.i.i.i.i.j.z.e.d.#.bQtQtQtQtQtQtQtQtQtQtQtQt",
".k.k.k.wQt.O.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.P.k.k.k.k.k.L.#.d.Q.N.R.R.y.y.y.y.y.y.y.y.i.i.i.i.i.j.s.e.d.#.bQtQtQtQtQtQtQtQtQtQtQt",
".k.k.uQt.B.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.S.v.v.v.T.#.U.V.N.R.R.R.R.y.y.y.y.y.y.y.y.y.y.y.y.y.y.s.e.d.#.bQtQtQtQtQtQtQtQtQtQt",
".k.oQt.W.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.C.i.i.T.#.U.X.N.R.R.R.R.R.R.R.R.y.r.r.r.r.r.r.r.r.r.Y.Y.s.e.d.#.bQtQtQtQtQtQtQtQtQt",
".k.pQt.B.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.0.#.U.X.1.2.2.2.2.2.2.2.2.r.N.N.N.N.N.N.f.f.f.f.f.f.3.g.e.d.#.bQtQtQtQtQtQtQtQt",
".k.pQt.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.0.#.4.5.6.7.7.7.7.7.7.7.8.N.1.1.1.1.1.1.1.1.1.g.g.g.g.g.s.9.e.d.#.bQtQtQtQtQtQtQt",
".k.p.y.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.0.#.#.U.U#.#.#.#..d####.m#a#b.1.1.1.1.1.1.1.1.g.E.X#c#c#c#c#c#c#c.#.#.bQtQtQtQtQtQt",
".k.p.y#d#d#d#d#d#d#d#d#d#d#d#d#d#d#d#d#d#d#e.#.#.#.#.#.#.#.#.#.#.#.#.##f.6#g#g#g#g#g#g#g#g.8.E#h.#.#.#.#.#.#.#.#.#.#.bQtQtQtQtQt",
".k.p.y#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#j.###.V#k#k#k#k#k#k#k#k.E.V.##lQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".k.p.y#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#n.4#o#p.g.g.g.g.g.g#b#q.m.#.k#r#s.K.K.K.l.l.l.k.k.k.k.KQtQt",
".k.p.R#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m.0#h#f.8#p#p#p#p#p#p.E#q.4#t.k.k.k.k.k.k.k.k.p.p.p.q.k.lQtQt",
".k.p.R#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#v.##f.7#b#b#b#b#b#b.V#c.##v.u#w.v.v.wQtQtQtQtQtQt#x#y.kQtQt",
".k.p.R#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#A#B.##C.6.8.8.8.8.8.x.V.m.#.R#x.WQtQtQt#x#x#x.i.i.R.R.o.kQtQt",
".k.p#D#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#E.o#F.#.5.6.7.7.7.7.7.Q#a.#.T#G.S.i.i.i.i.i.R.R.R.R.R#H.kQtQtQt",
".k.p#D#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#I#J.k.o#v.#.5.Q.6.6.6.x.6#a.d.##G#G.S.i.i.R.R.R.R.R.R.R.R.H.kQtQtQt",
".k.p#D#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#L.o.k.p.R#M.#.5.Q.6.6.6.6.V#f.#.T.B.S#G.R.R.R.R.R.R.R.R.R.v.k.lQtQtQt",
".k.k#D#I#I#I#I#I#I#I#I#I#I#I#I#I#I#I#I#I#I#I#I#I#I#I#I#I#N.k.o#wQt#x.T.##C.Q.Q.Q.M.Q#f.4#h#O.F#P.A#Q#Q#D#D#R#R#R#R#R.t.kQtQtQtQt",
".k.k#D#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#S#T#U.k.q.w.W#R.C#V.4#f.X.Q.Q.Q#o.d.##W.C.C#P#P.B.B.B.B.B.B.B.B.B.o.kQtQtQtQt",
".k.k#D#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#E#Y#Z#0#1.k.k#2Qt#x.C.D#3.##.#c.X.X.X#o.5.#.c.D.D.D#4#4.F.C.C.C.C.C.C.C#5.kQtQtQtQtQt",
".k.k#6#X#X#X#X#X#X#X#X#X#X#Z#Y#J#0#J#7.o.k.k.k.k.k.k#y.AQt.y#8#8#8#e.#.5#c#c#o#f.5#h#h#9#8#8#8#5#5.C.C.C.C.C.C.C.C.H.kQtQtQtQtQt",
".k.k.C#T#T#T#T#T#T#T#T#T#1.k.k.k.k.k.k#y.pa..u.u.A.RQtQt.C.O.O.Oa##h.4#C#o#o#f.5#h#h#3.O.O.O.Oaaaa#8#8#8#8#8#8#8ab.k.lQtQtQtQtQt",
".k.kac#T#T#T#T#T#T#T#E#1.k.q.u.S.v.RQtQtQtQt.y.y.y.B#8.G.G.G.G.G#e.#ad#f#f#C.5#h.##W.G.G.G.G.G#jaeabababababababaf.kQtQtQtQtQtQt",
".k.kag#T#T#T#T#T#T#T#1.k#2ah#x#Q.F.F#8#8.Z.Z.Z.Z.Z.Z.Z.Z.Z.Z.Zai.#.4#C#C#Cad.#.##W.Z.Z.Z.Z.Z.Zajae.G.G.G.Z.Z.Z.Z.o.kQtQtQtQtQtQt",
".k.k#m#T#T#T#T#T#T#Y.k.qQt#R.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.Pak#h#h.5#C.5#..##hak.P.P.P.P.P.P.Pajal.Z.Z.Z.Z.Z.Zaj.kQtQtQtQtQtQtQt",
".k.k#u#E#E#E#E#E#E#U.k.w.y.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.Pak#h.#ad.5.5.4.##nam.P.P.P.P.P.P.P.Pajal.Z.Zagag#d#d#0.kQtQtQtQtQtQtQt",
".k.k#u#E#E#E#E#E#Z.k#2Qt.Z.P.P.P.P.P.P.P.P.P.P.P.P.P.P.Pai#h.#ad.5.U.#.##v.P.P.P.P.P.P.P.P.P.Pajal#d#d#d#d#dan.k.lQtQtQtQtQtQtQt",
".k.k#u#E#E#E#E#E#N.k.R#R#d#d#d#d#d#d#d#d#d#d#d#d#d#d#d#v.#.##..4.#.#.cam#d#d#d#d#d#d#d#d#d#d#d#Ial#d#d#d#d#d#E.kQtQtQtQtQtQtQtQt",
".k.kao#E#E#E#E#E#U.qQt.Z#i#i#i#i#i#i#i#i#i#i#i#i#iai#n.#.##h.#.#.0ai#i#i#i#i#i#i#i#i#i#i#i#i#i#I.I#i#i#m#m#m.o.kQtQtQtQtQtQtQtQt",
".k.kao#Z#Z#Z#Z#Z.k#w.i#i#i#i#i#i#i#i#i#i#i#i#i#i.c.#.#.#.##V#vap#i#i#i#i#i#i#i#i#i#i#i#i#i#i#u#Iap#m#m#m#m#I.kQtQtQtQtQtQtQtQtQt",
".k.kao#Z#Z#Z#Z#N.k.R.C#i#i#i#i#i#i#i#i#i#i#i#i#i#n#n.0#vak#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#u#Iaf#m#m#m#maq.kQtQtQtQtQtQtQtQtQt",
".k.kao#Z#Z#Z#Z#1a.Qtag#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#m#u#L#2#u#u#u#A.o.kQtQtQtQtQtQtQtQtQt",
".k.kao#Z#Z#Z#Y.k.A.i#u#u#u#u#u#u#u#u#u#u#u#u#u#s#s#s#s#s#u#u#u#u#s#s#u#u#u#u#u#u#u#u#u#u#u#s#s#L#2#z#s#s#Z.kQtQtQtQtQtQtQtQtQtQt",
".k.k#A#Z#Z#Z#0.kQt.C#u#u#u#u#u#u#u#u#u#u#u#u#u#s#s#u#u#s#s#u#u#u#s#s#u#u#u#u#u#u#u#u#u#u#u#s#s#L#2#z#s#s#1.kQtQtQtQtQtQtQtQtQtQt",
".k.k#A#Y#Y#Y#1a.Qtar#u#u#u#u#u#u#u#u#u#u#u#u#u#s#s#u#u#u#s#s#u#u#u#u#u#u#u#u#u#u#u#u#u#u#u#s#s#L#2#z#s#s.kQtQtQtQtQtQtQtQtQtQtQt",
".k.k#A#Y#Y#Y.k.A#D#z#z#z#z#z#z#z#z#z#z#z#z#z#z#s#s#z#z#z#s#s#z#z#s#s#z#z#s#s#s#s#z#z#z#z#z#s#s#E#2#z#s#s.kQt#s#sQt#s#sQtQtQtQtQt",
".k.k#A#Y#Y#0.kQtac#z#z#z#z#z#z#z#z#z#z#z#z#z#z#s#s#z#z#z#s#s#z#z#s#s#z#z#s#s#z#z#z#z#z#z#z#s#s#E#2#A#s#s.kQt#s#s#sQt#s#sQtQtQtQt",
".k.k#u#Y#Yas#2Qt#zatatatatatatatatatatatatatat#s#satatat#s#satat#s#satat#s#satatatatatatat#s#s#Ea.#K#s#sQtQt#s#sQtQt#s#sQtQtQtQt",
".k.k#i#Y#N.k.S#6atatatatatatatatatatatatatatat#s#satatat#s#satat#s#satat#s#satatatatatatat#s#s#Ea.#K#s#sQtQt#s#sQtQt#s#sQtQtQtQt",
".k.k#i#Yaq.oQtac#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#s#s#K#K#K#s#s#K#K#s#s#K#K#s#s#K#K#K#K#K#K#K#s#s#Za.#L#s#sQtQt#s#sQtQt#s#sQtQtQtQt",
".k.k#i#Yas#2Qt#z#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#s#s#K#K#s#s#K#K#K#s#s#K#K#s#s#K#K#K#K#K#K#I#s#s#Za.#y#s#sQtQt#s#s#sQt#s#sQtQtQtQt",
".l.kau#N.k.S#6#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#s#s#s#s#s#K#K#K#K#s#s#K#K#s#s#K#I#X#L#E#Z#Z#N#s#s#s#s#sQtQtQt#s#sQt#s#sQtQtQtQtQt",
".l.kavaq.oQtaw#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#I#X#L#E#Z#Z#N#0#U#1.k.k.k.k.k.KQtQtQtQt#s#sQtQtQtQtQtQtQtQt",
".l.kavas.tQt#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#I#X#L#E#Z#Z#Y#N#U#1.o.k.k.k.k.laxQtQtQtQtQtQtQtQt#s#sQtQtQtQtQtQtQtQt",
".l.kay.k.w#6#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#K#I#X#X#E#Z#Z#Z#N#J#1.o.k.k.k.k.k.KQtQtQtQtQtQtQtQtQtQtQtQtQt#s#sQtQtQtQtQtQtQtQt",
".l.k#U#yQtaw#K#K#K#K#K#K#K#K#K#K#K#K#K#I#X#X#E#Z#Z#Z#N#J#U#1.k.k.k.k.k.KQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".l.k.o.tQt#K#K#K#K#K#K#K#K#Kaz#I#X#E#E#Z#Z#N#0#U#1.o.k.k.k.k.JaxQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".l.k.k.w#6#K#K#K#Kaz#I#X#E#E#Z#Z#N#0#U#1.o.k.k.k.k.l.KQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".l.k#yQtar#I#X#E#E#Z#Z#N#0#U#1.o.k.k.k.k.k.KQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"Qt.k.o.S#Z#Z#N#J#U#1.o.k.k.k.k.k.KQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"Qt.l.k.o.o.k.k.k.k.k.k.KQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQt.K.k.k.KaxQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt"};

static const char* const img3_gemdDlg[] = { 
"64 64 119 2",
"#H c #392900",
"#I c #523100",
"#X c #634200",
"#V c #6b4a00",
"#W c #7b5208",
"#e c #845a08",
".o c #8c6308",
".d c #946308",
".t c #9c6b08",
"#J c #a56b08",
".a c #a57308",
".b c #ad7308",
".w c #ad7b08",
".# c #b57b08",
".c c #bd7b08",
".e c #bd8410",
".Z c #bd8c18",
"#S c #c68c10",
".Y c #c68c18",
"#L c #c69418",
".n c #c69429",
".X c #ce9421",
"#w c #ce9c21",
"#v c #ce9c29",
".f c #ce9c31",
"#c c #cea542",
".8 c #d69c29",
"#F c #d6a529",
"#p c #d6a531",
".W c #d6ad31",
".y c #d6ad42",
".g c #d6ad52",
"#u c #d6b542",
".p c #d6b563",
"Qt c #d9d9d9",
"#0 c #dea531",
".V c #dead39",
"#M c #dead42",
".J c #deb539",
".1 c #deb542",
"#O c #deb54a",
"#t c #deb552",
"#E c #debd4a",
"#x c #debd52",
"#l c #debd6b",
".h c #debd73",
"#Y c #dec652",
".s c #dec65a",
"#a c #dec67b",
".z c #dec684",
"#o c #e7ad39",
"#n c #e7ad42",
"#K c #e7b542",
"## c #e7bd4a",
".P c #e7c652",
".Q c #e7ce5a",
".4 c #e7ce8c",
"#i c #e7ce94",
"#D c #e7d663",
"#z c #e7d66b",
".i c #e7d6a5",
"#B c #efb54a",
"#h c #efbd4a",
"#g c #efc652",
"#. c #efc65a",
".U c #efce5a",
"#C c #efd663",
"#r c #efd67b",
"#j c #efd684",
".D c #efd68c",
"#d c #efd694",
".C c #efd69c",
"#k c #efde94",
".B c #efdead",
".A c #efdeb5",
".x c #efe7c6",
"#R c #f7c65a",
"#A c #f7c663",
"#s c #f7c66b",
"#Q c #f7ce5a",
".5 c #f7ce63",
"#U c #f7ce6b",
"#m c #f7ce73",
"#f c #f7ce7b",
"#N c #f7d663",
".T c #f7d66b",
"#Z c #f7d673",
"#b c #f7d67b",
".7 c #f7d684",
"#G c #f7de6b",
".S c #f7de73",
".0 c #f7de84",
".v c #f7e773",
".I c #f7e77b",
"#y c #f7e784",
".H c #f7e78c",
".R c #f7e794",
".r c #f7ef84",
".K c #f7ef8c",
".O c #f7ef94",
".N c #f7ef9c",
".u c #f7efa5",
".F c #f7efad",
".M c #f7efb5",
".9 c #f7efbd",
".2 c #f7efd6",
".m c #f7f7c6",
".k c #f7f7ce",
".L c #f7f7d6",
".j c #f7f7de",
"#P c #ffde8c",
"#T c #ffde9c",
".G c #ffe79c",
".E c #ffe7ad",
".l c #fff7bd",
"#q c #fff7de",
".6 c #fff7e7",
".3 c #fff7ef",
".q c #fffff7",
"QtQtQtQt.#.a.b.b.b.b.#.#.#.#.c.#.dQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQt.#.c.c.e.f.f.f.g.h.h.h.i.g.cQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQt.#.c.iQtQtQtQt.j.j.j.k.l.l.m.n.oQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"Qt.#.c.p.q.r.r.r.r.r.r.r.r.r.r.r.s.cQtQtQtQtQtQtQtQtQtQtQtQtQt.#.a.a.a.a.tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"Qt.#.nQt.u.r.r.r.r.r.r.r.r.r.r.r.v.c.a.a.w.#.#.#.#.c.c.c.c.c.c.c.c.c.c.c.c.tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.c.x.j.r.r.r.r.r.r.r.r.r.r.r.r.r.y.p.h.h.h.h.h.z.A.A.B.i.C.D.E.F.G.H.I.J.cQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.gQt.K.r.r.r.r.r.r.r.r.r.r.r.r.r.F.j.j.j.j.j.L.l.l.M.F.u.N.O.K.r.r.I.I.P.cQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".c.A.m.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.Q.cQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".c.A.O.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.Q.cQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".c.A.R.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.P.cQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".c.A.H.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.P.cQtQtQt.#.a.a.w.b.bQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".c.A.H.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.U.V.W.W.W.W.X.Y.c.b.c.c.c.c.e.f.f.Z.aQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".c.A.0.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.1.Y.c.e.f.f.f.h.h.h.i.A.A.2QtQtQt.3.3.4.cQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".c.i.0.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.P.Y.c.g.iQt.3.3.3.j.j.L.x.6.j.j.L.2.2.2.2.g.tQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".w.h.7.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.8.c.g.2.3.L.m.9.9.9.9.9.M.i.j.L.L.2.2.2.2.2.eQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".w.h.7#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.##.Y.Y.A.3.k.9.9.9.9.9.9.9.9.M.C.L.2.2.2.k.k.k#a.cQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.h#b#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#..V.e#c.6.L.M.F.F.F.F.F.F.F.F.F.u#d.m.m.m.9.9.9.9.n#eQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.h#f#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#h.V.Y.e#i.q.M.u.u.u.u.u.u.u.u.u.u.u.N#j.M.M.M.F.F.F#k.cQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".##l#m#h#h#h#h#h#h#h#n#o#p.8.X.Y.e.c.c.c#c.x#q.N.O.O.O.O.O.O.O.O.O.O.O.O.H#r.u.u.u.u.N.N.y.aQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.p#s#h#h#h#h#h#n.e.c.c.Z.f#c.h#a.i.z.B.z#t#u#u#v#w#w#w.c.e#x.K.K.K.K.K#y#z.R.R.R.R.H.H.eQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".##t#A#B#B#B#B#n.e.n.2QtQt.L.L.l.M#c.c.c.e.f.f.f.g.h.h.h.i.g.c#C.I.I.I.I.v#D#y#y#y#y#y#E.cQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.y#.#B#B#B#B.Y.n.6.F.I.I.I.I.I#E.c.iQtQtQtQt.j.j.j.k.l.l.m.n#F.I.I.I.I#G.Q#y.I.I.I.I.X#eQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.V#g#B#B#B#n.c.A.M.v.v.v.v.v.U.c.p.q.r.r.r.r.r.r.r.r.r.r.r.s.c#G.v.v.v#C.s.I.S.S.S#C.c#H#I#e#J.a.a.tQtQtQtQtQtQtQtQtQtQtQtQtQt",
".#.W#h#K#K#K#v.g.6.v.v.v.v.v.v#L.nQt.u.r.r.r.r.r.r.r.r.r.r.r.v.c#L.X.X.X#L.Y.Z.c.c.c.c.c.c.c.c.c.c.c.c.tQtQtQtQtQtQtQtQtQtQtQtQt",
".#.W###K#K#K.e.i.N#G#G#G#G#G.1.c.x.j.r.r.r.r.r.r.r.r.r.r.r.r.r.y.p.h.h.h.h.h.z.A.A.B.i.C.D.E.F.G.H.I.J.cQtQtQtQtQtQtQtQtQtQtQtQt",
".#.W###K#K.V.YQt.S#G#G#G#G#G.Z.gQt.K.r.r.r.r.r.r.r.r.r.r.r.r.r.F.j.j.j.j.j.L.l.l.M.F.u.N.O.K.r.r.I.I.P.cQtQtQtQtQtQtQtQtQtQtQtQt",
".#.W###M#M.X.p.k#G#G#G#G#G#G.c.A.m.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.Q.cQtQtQtQtQtQtQtQtQtQtQtQt",
".#.W###M#M.e.x.G.T.T.T.T.T.T.c.A.O.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.Q.cQtQtQtQtQtQtQtQtQtQtQtQt",
".#.W###M#p.Y.3.T#N#N#N#N#N#N.c.A.R.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.P.cQtQtQtQtQtQtQtQtQtQtQtQt",
".#.W#E.y.Y.p.9#N#N#N#N#N#N#N.c.A.H.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.P.cQtQtQt.#.a.a.w.b.bQtQtQt",
".#.W#O.y.e.2#P.5.5.5.5.5.5.5.c.A.H.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.U.V.W.W.W.W.X.Y.c.b.c.c.c.c.e.f.f.Z.aQtQt",
".#.W.1#v.n.3#Q#Q#Q#Q#Q#Q#Q#Q.c.A.0.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.1.Y.c.e.f.f.f.h.h.h.i.A.A.2QtQtQt.3.3.4.cQtQt",
".#.W.1.Y.z.9#Q#Q#Q#Q#Q#Q#Q#Q.c.i.0.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.P.Y.c.g.iQt.3.3.3.j.j.L.x.6.j.j.L.2.2.2.2.g.tQtQt",
".#.W.1.e.2#b#R#R#R#R#R#R#R#R#L.h.7.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.8.c.g.2.3.L.m.9.9.9.9.9.M.i.j.L.L.2.2.2.2.2.eQtQtQt",
".#.W#p.n.6#R#R#R#R#R#R#R#R#R.Y.h.7#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.##.Y.Y.A.3.k.9.9.9.9.9.9.9.9.M.C.L.2.2.2.k.k.k#a.cQtQtQt",
".#.W.X#i.E#R#R#R#R#R#R#R#R#R.Y.h#b#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#..V.e#c.6.L.M.F.F.F.F.F.F.F.F.F.u#d.m.m.m.9.9.9.9.nQtQtQtQt",
".##F.c.6#m#R#R#R#R#R#R#R#R#R.Y.h#f#g#g#g#g#g#g#g#g#g#g#g#g#g#g#g#h.V.Y.e#i.q.M.u.u.u.u.u.u.u.u.u.u.u.N#j.M.M.M.F.F.F#k.cQtQtQtQt",
".##S#c.6#R#R#R#R#R#R#R#R#R#R.Y#l#m#h#h#h#h#h#h#h#n#o#p.8.X.Y.e.c.c.c#c.x#q.N.O.O.O.O.O.O.O.O.O.O.O.O.H#r.u.u.u.u.N.N.y.aQtQtQtQt",
".a.c#i#T#R#R#R#R#R#R#R#R#R#R.Y.p#s#h#h#h#h#h#n.e.c.c.Z.f#c.h#a.i.A.q.3.l.K.K.K.K.K.K.K.K.K.K.K.K.K.K#y#z.R.R.R.R.H.H.eQtQtQtQtQt",
".a.c.6#U#R#R#R#R#R#R#R#g#n#p.e#t#A#B#B#B#B#n.e.n.2QtQt.L.L.l.M.F.N.O.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.v#D#y#y#y#y#y#E.cQtQtQtQtQt",
".b.f.2#R#R#R#g#n#p.X.e.c.c.a.w.y#.#B#B#B#B.Y.n.6.F.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I#G.Q#y.I.I.I.I.XQtQtQtQtQtQt",
"#J.c.8#F.Y.e.c.c.a.o#VQtQtQt.t.V#g#B#B#B#n.c.A.M.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v#C.s.I.S.S.S#C.cQtQtQtQtQtQt",
"Qt.t.c.t#W#XQtQtQtQtQtQtQtQt.b.W#h#K#K#K#v.g.6.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v.v#C.s.S.S.S.S#p.aQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.W###K#K#K.e.i.N#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#C#Y#Z.T.T.T.eQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.W###K#K.V.YQt.S#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G.U#x.T.T.T.1.cQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.W###M#M.X.p.k#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G.U#x#C#C#C.Z#eQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.W###M#M.e.x.G.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.U#E.5.5.P.cQtQtQtQtQtQtQtQt",
"QtQtQtQt#H#H#H#H#HQtQtQtQtQt.#.W###M#p.Y.3.T#N#N#N#N#N#N#N#N#N#N#N#N#N#H#H#H#H#H#N#N#N#N#H#H#N#N#N#N#.#O.5.5.8.aQtQtQtQtQtQtQtQt",
"QtQtQtQt#H#HQtQt#H#HQtQtQtQt.#.W#E.y.Y.p.9#N#N#N#N#N#N#N#H#N#N#N#N#N#N#H#H#N#N#H#H#N#N#N#H#H#N#N#N#N#g#O.U.U.eQtQtQtQtQtQtQtQtQt",
"QtQtQtQt#H#HQtQtQt#H#HQtQtQt.#.W#O.y.e.2#P.5.5.5.5.5.5#H#H.5.5.5.5.5.5#H#H.5.5.5#H#H.5.5.5.5.5.5.5.5#g#O#..V.cQtQtQtQtQtQtQtQtQt",
"QtQtQtQt#H#HQtQtQt#H#HQtQtQt#H#H#H#H.n.3#Q#H#H#H#H#Q#H#H#H#H#Q#Q#Q#Q#Q#H#H#Q#Q#Q#H#H#Q#Q#H#H#Q#Q#H#H#H#H#..e.oQtQtQtQtQtQtQtQtQt",
"QtQtQtQt#H#HQtQtQt#H#HQtQt#H#H.W.1#H#H.9#H#H#Q#Q#H#H#Q#H#H#Q#Q#Q#Q#Q#Q#H#H#Q#Q#Q#H#H#Q#Q#H#H#Q#Q#H#H#h#M##.cQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQt#H#HQtQtQt#H#HQtQt#H#H.W.1#H#H#b#H#H#H#R#R#R#R#H#H#R#R#R#R#R#R#H#H#R#R#R#H#H#R#R#H#H#R#R#H#H#h#M.Z.aQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQt#H#HQtQtQt#H#HQtQt#H#H#H#H#H#H#R#R#H#H#H#H#R#R#H#H#R#R#R#R#R#R#H#H#R#R#R#H#H#R#R#H#H#R#R#H#H#0.n.eQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQt#H#HQtQtQt#H#HQtQt#H#H.W.X#i.E#R#R#R#R#H#H#H#R#H#H#R#R#R#R#R#R#H#H#R#R#R#H#H#R#R#H#H#0#w#H#H.c.aQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQt#H#HQtQt#H#HQtQtQt#H#H#F.c#H#H#R#H#H#R#R#H#H#R#H#H#R#R#R#R#R#R#H#H#R#R#H#H.V.8.Y#H#H.w.d#H#HQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQt#H#H#H#H#HQtQtQtQtQt#H#H#H#H#R#R#R#H#H#H#H#R#R#R#H#H#R#R#R#R#R#H#H#H#H#H.c.c.d#W#H#HQtQt#H#HQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.a.c#i#T#R#R#R#R#R#R#R#R#R#R#R#R#g#o#F#L.e.c.c.t#eQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.a.c.6#U#R#R#R#R#R#R#R#g#n#p.X.e.c.c.a.oQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.b.f.2#R#R#R#g#n#p.X.e.c.c.a.o#VQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt#J.c.8#F.Y.e.c.c.a.o#VQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.t.c.t#W#XQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt"};

static const char* const img4_gemdDlg[] = { 
"64 64 211 2",
"#k c #004a00",
"ao c #005200",
"ai c #005a00",
"aM c #006300",
"aC c #006b00",
"a3 c #007300",
"aG c #007f00",
"aP c #085208",
"aH c #085a00",
"a2 c #085a10",
"ay c #086f00",
"#m c #088c00",
"aJ c #088c08",
"#9 c #0d8b08",
"#3 c #109c08",
"aB c #186308",
"#V c #1da115",
"a4 c #20851e",
"az c #296b10",
"ae c #317310",
"ap c #39a836",
"av c #4a8526",
".p c #525a6b",
"#W c #52b939",
"aW c #56875e",
".x c #5a5a73",
".k c #63637b",
"ad c #64dc45",
"bp c #6b4a00",
".Y c #6b7384",
".d c #73738c",
"ax c #73c06d",
"#n c #73ef42",
"#o c #73f742",
"#p c #78ec4f",
".a c #7b8397",
"a. c #7bd86b",
"#r c #7be75a",
"#E c #7bff42",
"#t c #81e760",
"ba c #845a08",
"a5 c #849c31",
"aX c #849c39",
"aK c #84a539",
"aj c #84a542",
"#u c #84e76b",
"#b c #8c6308",
".X c #8c94a5",
".# c #8c94b5",
"#. c #8c9cad",
"#x c #90e777",
"aS c #946308",
".9 c #949cad",
".0 c #949cbd",
".W c #94a5b5",
"aR c #94ad42",
"#C c #94dc8a",
"#a c #9c6b08",
".o c #9c9cbd",
".j c #9ca5c6",
"#D c #9ce784",
".s c #a57308",
".N c #a5adb5",
".8 c #a5adc6",
".f c #a5bdce",
".h c #a5bdd6",
"#H c #a5de9c",
".r c #ad7308",
".t c #ad7b08",
"#A c #ad8429",
".M c #adb5bd",
".c c #adb5ce",
"an c #adb94a",
".7 c #adbdce",
".Z c #adbdd6",
"#J c #ade79c",
"#2 c #b1ca90",
"#I c #b3e9ad",
".q c #b57b08",
"#F c #b5a594",
"#v c #b5ad94",
".L c #b5bdc6",
".6 c #b5c6da",
".l c #b5cee2",
"aV c #b5d6c6",
"#4 c #b7d2a4",
"ag c #bcbd69",
".u c #bd7b08",
".y c #bd8410",
"#K c #bd8c21",
".e c #bdcede",
"#c c #bdcee7",
"a8 c #bdd6c6",
".v c #bdd6ef",
"#N c #bde7bd",
"bl c #c68c10",
"a7 c #c68c18",
".A c #c69429",
".z c #c69c39",
".K c #c6cada",
".b c #c6deff",
"aD c #c6efc6",
"#0 c #ce9421",
"b. c #ce9c21",
".3 c #cea539",
"bc c #cea542",
".5 c #cedeef",
"#f c #cedef7",
"a1 c #cee7d6",
".V c #cee7f7",
".B c #cee7ff",
"#M c #ceefc6",
"aw c #ceefce",
"aU c #d69c29",
"aI c #d6a529",
"bb c #d6a542",
"be c #d6a935",
"b# c #d6ad42",
"a6 c #d6ad4a",
"#6 c #d6ad52",
"aT c #d6b552",
".F c #d6b563",
"aQ c #d6bd52",
"#z c #d6bd84",
"aF c #d6d663",
"aq c #d6d66b",
".n c #d6e7f7",
".4 c #d6e7ff",
"ah c #d6efce",
"#Q c #d6efd6",
"Qt c #d9d9d9",
".G c #dab96f",
"at c #dbba47",
"bi c #dea531",
"aZ c #deb139",
"## c #dec652",
"aE c #dec65a",
"as c #dece63",
"ac c #dedead",
"#7 c #dedeb5",
"#5 c #dedebd",
"#Y c #dedec6",
"#S c #deded6",
".J c #dee7f7",
".C c #dee7ff",
".g c #deefff",
"bh c #e7ad39",
"a9 c #e7b542",
"aY c #e7bd4a",
"bj c #e7c64a",
"aN c #e7c652",
"aA c #e7ce5a",
"ak c #e7ce6b",
"#T c #e7ce8c",
".O c #e7ce94",
"ar c #e7d663",
"a# c #e7d67b",
"bf c #e7d6a5",
"#y c #e7d6b5",
"#1 c #e7e7d6",
"#O c #e7e7de",
"#8 c #e7efb5",
".E c #e7efff",
".w c #e7f7ff",
"bo c #ecba42",
"bg c #efbd4a",
"#X c #efc652",
"bd c #efce52",
"aL c #efd66b",
".H c #efdeb5",
".I c #efe7c6",
".i c #eff7ff",
"bm c #f7c652",
"#U c #f7c65a",
"a0 c #f7ce5a",
"#L c #f7ce63",
"aO c #f7d65a",
"#G c #f7d663",
"#w c #f7d66b",
"bn c #f7d673",
"#s c #f7de6b",
"#q c #f7de73",
"au c #f7de7b",
"am c #f7de94",
"bq c #f7de9c",
"#e c #f7e773",
"#l c #f7e77b",
"al c #f7e78c",
".U c #f7e7ad",
"aa c #f7e7b5",
".2 c #f7ef84",
"#d c #f7ef8c",
"ab c #f7ef94",
".T c #f7ef9c",
"#i c #f7efa5",
".S c #f7efad",
".R c #f7f7bd",
".D c #f7f7ff",
".m c #f7ffff",
"bk c #ffde84",
"af c #ffe7a5",
"#P c #ffefce",
"#B c #ffefd6",
".1 c #fff7b5",
"#Z c #fff7c6",
"#j c #fff7ce",
".Q c #fff7d6",
".P c #fff7de",
"#g c #fff7ef",
"#R c #ffffe7",
"#h c #fffff7",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.aQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.b.b.b.b.b.b.b.b.b.b.b.b.b.b.c.dQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.b.b.b.b.b.b.b.b.b.b.b.b.b.b.e.c.dQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.b.b.b.b.b.b.b.b.b.b.b.b.b.b.f.g.c.dQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.b.b.b.b.b.b.b.b.b.b.b.b.b.b.h.i.g.j.kQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.b.b.b.b.b.b.b.b.b.b.b.b.b.b.l.m.i.n.o.pQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQt.q.r.s.s.t.r.r.r.q.q.q.q.u.u.tQtQtQtQtQtQtQtQtQtQtQt.#.b.b.b.b.b.b.b.b.b.b.b.b.b.b.vQt.m.w.n.o.xQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQt.q.u.u.u.u.u.u.u.u.u.u.u.u.y.z.A.u.sQtQtQtQtQtQtQtQtQtQt.#.B.B.B.B.B.B.B.B.B.B.B.B.B.B.CQtQt.D.E.n.o.xQtQtQtQtQtQtQtQtQt",
"QtQtQt.q.u.y.F.G.G.G.H.H.H.IQtQtQtQtQtQt.z.uQtQtQtQtQtQtQtQtQtQt.#.B.B.B.B.B.B.B.B.B.B.B.B.B.B.J.K.L.M.N.K.n.#.xQtQtQtQtQtQtQtQt",
"QtQt.t.q.u.OQtQtQt.P.P.P.Q.R.R.R.S.T.T.T.U.u.rQtQtQtQtQtQtQtQtQt.#.B.B.B.B.B.B.B.B.B.B.B.B.B.V.f.W.X.a.d.Y.d.Z.0QtQtQtQtQtQtQtQt",
"QtQt.q.u.FQt.1.2.2.2.2.2.2.2.2.2.2.2.2.2.2.3.uQtQtQtQtQtQtQtQtQt.#.4.4.4.4.4.4.4.4.4.4.4.4.4.5.6.7.8.W.9#..X.X.#QtQtQtQtQtQtQtQt",
"Qt.q.u.AQt.P.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2##.u#a#b.s.r.q.q.q.q.q.#.4.4.4.4.4.4.4.4.4.4.4.4.4.4.5#c.e.6.Z.7.7.7.#QtQtQtQtQtQtQtQt",
".t.q.u.IQt#d.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2#e.u.u.u.u.u.u.u.u.u.u.#.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.n#f.n.n.5.5.#QtQtQtQtQtQtQtQt",
".q.u.GQt.R.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.O.H.H.H.HQtQtQtQtQt.#.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.#QtQtQtQtQtQtQtQt",
".q.y#g#h.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2#i.P.P.P.P#j.R.R.R.R.#.g.g.g.g.g.g.g#k#k.g.g.g.g.g.g.g.g.g.g.g.g.g.#QtQtQtQtQtQtQtQt",
".u.zQt.R#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l.#.g.g.g.g.g.g#k#m#m#k.g.g.g.g.g.g.g.g.g.g.g.g.#QtQtQtQtQtQtQtQt",
".u.zQt#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l.#.g.g.g.g.g#k#m#n#o#m#k.g.g.g.g.g.g.g.g.g.g.g.#QtQtQtQtQtQtQtQt",
".u.z.Q#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e.#.E.E.E.E#k#m#p#p#n#o#m#k.E.E.E.E.E.E.E.E.E.E.#QtQtQtQtQtQtQtQt",
".u.z.Q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q.#.E.E.E#k#m#r#r#p#p#n#o#m#k.E.E.E.E.E.E.E.E.E.#QtQtQtQtQtQtQtQt",
".u.z.Q#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s.#.E.E#k#m#t#u#t#r#p#p#n#o#m#k.E.E.E.E.E.E.E.E.#QtQtQtQtQtQtQtQt",
".u.z.Q.#.#.#.#.#.#.#.#.#.#.#.#.#.#.##v#w#w#w#w#w#w#w#w#w#w#w#w#w.#.i#k#m#u#x#u#u#t#r#p#p#n#o#m#k.i#y#y#z.G.G.z#A#a.u.u.u.qQtQtQt",
".u.z#B.#.b.b.b.b.b.b.b.b.b.b.b.b.b.b.c#v#w#w#w#w#w#w#w#w#w#w#w#w.##k#m#C#D#D#x#x#u#t#r#p#p#n#E#m#k.u.u.u.u.u.u.u.z.z.z.A.u.rQtQt",
".u.z#B.#.b.b.b.b.b.b.b.b.b.b.b.b.b.b.e.c#F#G#G#G#G#G#G#G#G#G#G#G#k#m#H#I#J#D#D#x#x#u#t#r#p#p#n#E#m#k.H.H.IQtQtQtQtQtQt.P#K.uQtQt",
".u.z#B.#.b.b.b.b.b.b.b.b.b.b.b.b.b.b.f.g.c#F#L#L#L#L#L#L#L#L#L#k#m#I#M#N#I#J#H#D#x#x#u#t#r#p#p#n#E#m#k#g#g#g#g#O.P.P.Q.Q.y.tQtQt",
".u.z#P.#.b.b.b.b.b.b.b.b.b.b.b.b.b.b.h.i.g.j#v#L#L#L#L#L#L#L#k#m#H#Q#Q#M#N#I#J#H#D#x#u#u#t#r#p#p#n#E#m#k#R#R#R#S.Q.Q.Q#T.uQtQtQt",
".u.z#P.#.b.b.b.b.b.b.b.b.b.b.b.b.b.b.l.m.i.n.o#z#U#U#U#U#U#k#m#H#Q#Q#Q#M#N#I#I#J#H#D#x#x#u#r#p#p#n#n#E#m#k#R#R#S.Q.Q.Q.3.uQtQtQt",
".u.z#P.#.b.b.b.b.b.b.b.b.b.b.b.b.b.b.vQt.m.w.n.o#z#U#U#U#k#m#m#m#m#m#m#m#m#V#H#I#J#H#D#x#u#W#m#m#m#m#m#m#m#k#R#S.Q.Q.H.u.sQtQtQt",
".q.u#P.#.B.B.B.B.B.B.B.B.B.B.B.B.B.B.CQtQt.D.E.n.o.G#X#k#k#k#k#k#k#k#k#k#k#V#C#N#I#J#H#D#x#W#k#k#k#k#k#k#k#k#k#Y#Z#Z.G.uQtQtQtQt",
".t.u#P.#.B.B.B.B.B.B.B.B.B.B.B.B.B.B.J.K.L.M.N.K.n.#.F#0.u.A.I#h#1#j#j#2#k#3#H#M#N#I#J#H#u#W#k#4#j#j#j#j#j#j#j#5.R.R.y.uQtQtQtQt",
".q.u#P.#.B.B.B.B.B.B.B.B.B.B.B.B.B.V.f.W.X.a.d.Y.d.Z.0.u#6#g#R.S#7#Z#Z#8#k#9#J#Q#M#N#I#Ja.#V#k#Z#Z#Z#Z#Z#Z#Z#Z#7.Sa#.u#bQtQtQtQt",
".q.uaa.#.4.4.4.4.4.4.4.4.4.4.4.4.4.5.6.7.8.W.9#..X.X.#.OQt.Qababacacac#4#k#9#Q#Q#Q#M#N#Iad#9aeacacacacacacacacac#i.3.uQtQtQtQtQt",
".q.uaf.#.4.4.4.4.4.4.4.4.4.4.4.4.4.4.5#c.e.6.Z.7.7.7.##g.S#d#d#d#d#d#dag#k#3ah#Q#Q#Q#M#N#Waiajakak.Tababababababal.u.sQtQtQtQtQt",
".q.uam.#.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.n#f.n.n.5.5.#.2.2.2.2.2.2.2.2anaoapahah#Q#Q#Q#I#V#kaqarasalalalalalalalat.uQtQtQtQtQtQt",
".q.uau.#.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.##l#l#l#l#l#l#l#lavaiapawahah#Q#Qaxayaz#laAas.2.2.2#l#l#l#l.y.uQtQtQtQtQtQt",
".q.u#w.#.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.##e#e#e#e#e#e#e#eaBaCaxawawahahaD#Vaoaj#eaAaE#l#l#l#l#l#laA.u#bQtQtQtQtQtQt",
".q.u#G.#.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.##e#e#e#e#e#e#eaF#kaG#NawawawahaxayaH#e#eaAaE#l#lauau#q#qaI.uQtQtQtQtQtQtQt",
".q.u#G.#.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.g.##e#e#e#e#e#e#eavaiapawawawaw#IaJaoaK#e#eaAaE#q#q#q#q#qaL.u.sQtQtQtQtQtQtQt",
".q.u#G.#.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.##q#q#q#q#q#qan#kaG#Cawawawaw#VaMaB#q#q#qaNaE#q#q#q#q#qat.uQtQtQtQtQtQtQtQt",
".q.uaO.#.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.##s#s#s#s#sanaPaCapawawawawapaCaPan#s#s#saNaQ#s#s#w#w#w.y.uQtQtQtQtQtQtQtQt",
".q.uaO.#.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.##s#s#s#saRaPaM#V#NawawawapaC#kaK#s#s#s#GaNaQ#w#w#w#waN.uaSQtQtQtQtQtQtQtQt",
".q.uaO.#.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.i.##s#sanae#kaC#V#Nawaw#I#VaC#kaK#s#s#s#s#GaNaT#w#w#w#waU.uQtQtQtQtQtQtQtQtQt",
".q.uaO.#.i.i.i.i.i.i.i.i.i.i.i.i.i.i#4#4#4.i.i.iaV#4aWavaH#kaMaGap#Naw#N#WaGaM#kaX#w#w#w#w#w#GaYaT#G#G#G#L.y.tQtQtQtQtQtQtQtQtQt",
".q.uaO.#.i.i.i.i.i.i.i.i.i.i.i.i.i.iaxav#k#k#k#k#kaoaiaMaC#9ap#Iaw#CapaGaCaoaBan#G#G#G#G#G#G#LaYaT#L#L#LaZ.uQtQtQtQtQtQtQtQtQtQt",
".q.ua0.#.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.Da1aWa2#k#kaiaCa3a4#V#Va4a3aCai#kaHa5#G#G#G#G#G#G#G#Ga0aYa6#L#L#La7.uQtQtQtQtQtQtQtQtQtQt",
".q.ua0.#.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.Da8aWa4aP#k#k#k#k#k#kazavan#G#G#G#G#G#G#G#G#G#Ga0aYa6#L#LaY.uaSQtQtQtQtQtQtQtQtQtQt",
".q.ua0.#.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.D.##L#L#L#L#L#L#L#L#L#L#L#L#L#L#L#L#L#L#La0a9a6#L#Lb..uQtQtQtQtQtQtQtQtQtQtQt",
".q.ua0.#QtQtQtQtQtQt#k#k#k#k#k#k#k#k#kQtQtQtQtQtQtQt.##L#L#L#L#k#L#L#L#L#L#L#L#L#L#L#L#L#L#L#Ua9a6#U#U.y.tQtQtQtQtQtQtQt#kQtQtQt",
".q.u#G.#QtQtQtQtQtQt#k#k#k#k#k#k#k#k#kQtQtQtQtQtQtQt.#a0a0a0#k#ka0a0a0a0a0a0a0a0a0a0a0a0a0a0#Xa9b##UaZ.ubaQtQtQtQtQtQt#k#kQtQtQt",
".q.u#s.#QtQtQtQtQtQt#k#kQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#a0a0a0#k#ka0a0a0a0a0a0a0a0a0a0a0a0a0a0#Xa9bb#Ua7.uQtQtQtQtQtQtQt#k#kQtQtQt",
".q.u#s.#QtQtQtQtQtQt#k#kQtQtQtQtQtQtQtQtQt#k#kQtQtQt#k#k#U#k#k#k#k#k#U#k#k#U#k#k#U#U#k#k#k#k#ka9bbaY.u#a#k#k#k#kQtQt#k#k#k#k#kQt",
".q.u#s.#.#.#.#.#.#.##k#k.#.#.#.#.#.#.#.#.##k#k#k.##k#k#k#U#k#k#k#k#k#U#k#k#k#k#k#U#k#k#k#k#k#k#kbc#K.u#k#k#k#k#k#kQt#k#k#k#k#kQt",
".r.ubdbe.ubfaa#U#U#U#k#k#k#k#k#k#k#k#k#U#U#U#k#k#U#k#k#U#U#U#k#k#U#U#U#k#k#k#U#Xbg#k#kbhbhbi#k#k.y.u#k#k#kQtQt#k#kQtQt#k#kQtQtQt",
".s.ubjb..yQtbk#U#U#U#k#k#k#k#k#k#k#k#k#U#U#U#U#k#k#k#U#U#U#U#k#k#U#U#X#k#ka9bhbhbiaU#0a7#k#k#k#k.uaS#k#kQtQtQtQtQtQtQt#k#kQtQtQt",
".r.ubjbl.F#g#U#U#U#U#k#k#U#U#U#U#U#U#U#U#U#U#U#k#k#k#U#U#U#X#k#ka9bhbh#k#k#0a7.y.u.u#k#k#k#k#k#kQtQt#k#kQtQtQtQtQtQtQt#k#kQtQtQt",
".r.uaZ.u.Iaa#U#U#U#U#k#k#U#U#U#U#U#U#U#U#U#U#U#k#k#kbga9a9bh#k#kb.a7.y#k#k.u.u.taS#k#k#kQtQt#k#kQtQt#k#kQtQtQtQtQtQtQt#k#kQtQtQt",
".r.u#0#KQtbk#U#U#U#U#k#k#U#U#U#U#U#U#U#Xbgbg#k#kbh#k#kaU#0a7#k#k.u.u.u#k#kQtQtQtQt#k#kQtQtQt#k#kQtQt#k#k#kQtQt#k#kQtQt#k#kQtQtQt",
".r.u.y.F#g#U#U#U#U#U#k#k#k#k#k#k#k#k#kbhbh#k#k#ka7#k#k#k.u.u#k#k#k#kQt#k#kQtQtQtQt#k#k#k#k#k#k#kQtQtQt#k#k#k#k#k#kQtQt#k#k#k#kQt",
".r.u.u.Iaa#U#U#U#Ubm#k#k#k#k#k#k#k#k#ka7.y#k#k.u.u.s#k#kQtQtQt#k#k#kQt#k#kQtQtQtQtQt#k#k#k#kQt#k#kQtQtQt#k#k#k#kQtQtQtQt#k#k#kQt",
".s.u#KQtbn#Xbgboa9bhbhbiaU#0a7.y.u.u.u.u.taSbpQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"Qt.u.ybqbhbhbiaU#0a7.y.u.u.u.u.taSbpQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"Qt.s.u.y.y.u.u.u.u.u.taSbpQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtaS.u.uaSbabpQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt"};

static const char* const img5_gemdDlg[] = { 
"64 64 106 2",
"#C c #000000",
".# c #007b08",
".w c #008000",
".Z c #008400",
".z c #008c08",
".Y c #009410",
".o c #009418",
".t c #009429",
".H c #009c10",
"#J c #00a518",
"#a c #00a521",
".V c #00a529",
".O c #00ad29",
"#K c #00b531",
".f c #08a531",
".F c #08b529",
".2 c #08b531",
"#L c #08bd39",
"#I c #10bd42",
".n c #18a542",
".u c #18ad39",
"#h c #18ad42",
".N c #18bd39",
"#b c #18bd42",
"#H c #18c642",
".R c #21b542",
"#M c #21c64a",
".S c #29c642",
"#G c #29ce52",
".1 c #31b552",
".5 c #31ce52",
"#E c #31d65a",
"#p c #39bd5a",
"#D c #39d65a",
".W c #42d65a",
".7 c #42d663",
"#g c #4abd63",
".8 c #4ad663",
"#A c #4ade63",
".e c #52bd73",
".3 c #52d66b",
"#z c #52de6b",
"#y c #52e76b",
"#k c #5ad673",
".x c #5ade6b",
"#w c #5ae76b",
".X c #63e773",
"#t c #63ef73",
".a c #6bc684",
".y c #6bce84",
".T c #6be77b",
"#q c #6bef73",
"#u c #6bef7b",
".g c #73ce8c",
"#s c #73d68c",
".I c #73ef7b",
"#o c #73f77b",
"#r c #7bde8c",
".A c #7bef7b",
".q c #7bef84",
"#l c #7bf77b",
"#i c #7bf784",
"#v c #84de94",
".B c #84f784",
"#e c #84f78c",
"#f c #8cd69c",
"#j c #8cf78c",
"#c c #8cf794",
"#F c #94e7a5",
".p c #94f794",
"#d c #94f79c",
"## c #9cdea5",
".0 c #9cdead",
"#B c #9cefad",
".r c #9cf79c",
".9 c #9cf7a5",
"#x c #a5efad",
".h c #a5f7a5",
".6 c #a5f7ad",
"#m c #a5ffa5",
".d c #addeb5",
".G c #adf7ad",
".4 c #adf7b5",
"#N c #b5e7c6",
".i c #b5f7b5",
".P c #b5f7bd",
"#. c #b5ffb5",
".v c #bde7c6",
".j c #bdf7bd",
".Q c #bdf7c6",
".k c #c6f7c6",
".J c #c6f7ce",
"#n c #c6ffc6",
".E c #cef7d6",
".M c #ceffce",
".c c #d6efd6",
".K c #d6ffd6",
"Qt c #d9d9d9",
".l c #deffde",
".s c #e7ffe7",
".m c #eff7ef",
".D c #efffef",
".C c #f7ffef",
".L c #f7fff7",
".U c #fffff7",
".b c #ffffff",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#.#QtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.#.#.a.a.b.b.c.d.d.d.a.e.e.e.f.#.#QtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.#.g.h.i.j.j.k.l.l.l.m.b.b.b.b.b.b.n.#QtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.o.p.q.q.q.q.q.q.q.q.q.q.q.q.r.r.s.m.t.#QtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.#.u.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.r.b.v.#.#QtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.w.#.#.x.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.k.b.a.#.#QtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.y.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.g.z.w.z.o.A.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.B.C.b.t.#QtQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.y.l.D.s.E.l.l.l.l.E.l.D.s.E.l.D.s.E.l.l.l.l.s.g.w.w.F.A.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.q.G.b.d.#.#QtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.s.g.z.w.H.I.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.A.m.b.#.#QtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.E.J.J.K.l.l.l.l.D.D.L.L.L.b.b.b.b.b.b.b.b.b.b.b.b.M.N.w.O.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.h.b.#.#QtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.P.P.P.P.P.P.P.j.Q.k.J.J.E.E.K.l.l.s.D.D.D.D.D.b.b.b.L.R.w.S.T.T.T.T.T.T.T.T.T.T.T.T.T.T.T.I.b.#.#QtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.P.P.P.P.P.P.P.P.P.j.Q.k.J.J.E.E.K.l.l.s.s.s.s.s.D.U.b.U.V.w.W.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.b.#.#QtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.P.P.P.P.P.P.P.P.P.P.P.j.Q.k.J.J.E.E.K.l.l.s.s.s.s.s.L.b.s.Y.Z.x.X.X.X.X.X.X.X.X.X.X.X.X.X.X.b.#.#QtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.P.P.P.P.P.P.P.P.P.P.P.P.P.j.Q.k.J.J.E.E.K.l.l.s.s.s.s.U.b.0.w.Y.x.x.x.x.x.x.x.x.x.x.x.x.x.x.b.#.#QtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.Q.k.k.J.E.K.K.K.l.l.s.b.b.1.w.2.3.3.3.3.3.3.3.3.3.3.3.3.3.b.#.#QtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.G.4.P.P.j.Q.k.J.M.M.K.s.b.s.Y.w.5.3.3.3.3.3.3.3.3.3.3.3.3.b.#.#QtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.6.6.G.i.i.P.j.j.k.k.D.b.0.w.w.N.7.8.8.8.8.8.8.8.8.8.8.b.#.#QtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.r.9.h.h.G.G.G.i#..j.b.b##.Y.w.w.Z#a.2#b.5.W.7.7.7.7.b.#.#QtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#c#c#c#c#c#c#c#c#c#c#c#c#c#c#c#c#c#c#c#c#c#c#c#d.r.r.9.h.h.G.J.b.b.U.g.f.Y.w.w.w.w.w.w.w.z#a.g.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#e#c#c.p#d.r.9.i.L.b.b.b.b.b.b.0#f#g#h.V.z.w.w.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i#i.B#e#j#c.p.p.G.J.l.s.s.b.b.b.b.b.b.U#k.w.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#i#i.B#e#e#j#c.p.p.r#m#.#n.M.D.b.L#a.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I.I#o#l#i#i.B#e#j#j#c.p.p.r#m.D.b#p.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q.I.I#l#i#i.B#e#e#c#c.p.M.b#r.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q#q.I.I.q.q#i#e#e#j.k.b#s.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#q#u#u.I.q.q.q.j.b#s.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X#t#q#u#u.I.P.b#v.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X#t.T.P.b#v.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w.X.4.b#r.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#w#x.b#s.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#y#x.b#s.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#z#x.b#s.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#x.b#s.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#x.b#s.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#A#B.b#s.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7#B.b#s.w.wQtQtQtQtQtQt",
"QtQtQt#C#CQtQt#C#C.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7.7#C#C#C.7.7.7.7.7.7.7#C#C.7.7.7.7.7#C#C.7.7.7#B.b#s.w.wQtQtQtQtQtQt",
"QtQtQt#C#CQtQt#C#C#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#C#C#D#D#D#D#D#D#D#D#D#C#C#D#D#D#D#D#C#C#D#D#D#B.b#s.w.wQtQtQtQtQtQt",
"QtQtQt#C#C#CQt#C#C#D#D#C#C#C#C#D#D#C#C#D#D#C#D#D#C#C#D#D#D#C#C#C#C#D#D#C#C#C#C#D#D#C#C#D#D#C#C#C#C#C#D#D#C#C#C#C.w.w#C#C#C#CQtQt",
"QtQtQt#C#C#CQt#C#C#E#C#C#E#E#C#C#E#C#C#E#C#C#C#E#C#C#E#E#E#E#C#C#E#E#C#C#E#E#C#C#E#C#C#E#C#C#E#E#C#C#E#C#C#F.b#C#C.w#C#CQtQtQtQt",
"QtQtQt#C#CQt#C#C#C#E#C#C#C#C#C#C#E#C#C#E#C#C#C#E#C#C#E#E#E#E#C#C#E#E#C#C#E#E#C#C#E#C#C#E#C#C#E#E#C#C#E#C#C#C#C#C#C.w#C#CQtQtQtQt",
"QtQtQt#C#CQt#C#C#C#G#C#C#G#G#G#G#G#G#C#C#C#G#C#C#C#G#G#G#G#G#C#C#G#G#C#C#G#G#C#C#G#C#C#G#C#C#G#G#C#C#G#C#C#F.b.y.w.w#C#CQtQtQtQt",
"QtQtQt#C#CQtQt#C#C#G#C#C#G#G#C#C#G#G#C#C#C#G#C#C#C#G#G#G#G#G#C#C#G#G#C#C#G#G#C#C#G#C#C#G#C#C#G#G#C#C#G#C#C#F.b#C#C.w#C#CQtQtQtQt",
"QtQtQt#C#CQtQt#C#C#G#G#C#C#C#C#G#G#G#C#C#G#G#G#C#C#G#G#G#G#G#C#C#G#G#G#C#C#C#C#G#G#C#C#G#G#C#C#C#C#C#G#G#C#C#C#C.w.w#C#CQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#F.b.y.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w#H#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#F.b.y.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQt.w.w.w.z.H.O#I#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#F.b.y.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.w.w.w.w.w.w.w.Y#J#K#H#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#F.b.y.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQt.w.w.w.w.w.w.Z.Y#a#L#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#F.b.y.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.w.w.w.w.w.w.w.z.H.O#I#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#F.b.y.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.w.w.w.w.w.w.w.Y#J#K#H#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#F.b.y.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.w.w.w.w.w.w.Z.Y#a#L#M#G#G#G#G#G#G#G#G#G#G#G#G#G#G#G#F.b.y.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.w.w.w.w.w.w.z.Y#a#L#M#G#G#G#G#G#G#G#G#G#G#F.b.y.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.w.w.w.w.w.w.w.z.Y#a#L#M#G#G#G#G#G#F.b#p.w.wQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.w.w.w.w.w.w.w.z.Y#a#K#I#F#N.w.wQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.w.w.w.w.w.w.w.w.w.w.wQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.w.w.w.w.wQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt"};

static const char* const img6_gemdDlg[] = { 
"48 48 122 2",
"#U c #8c5252",
"#X c #8c5a52",
"#K c #945252",
"#P c #945a52",
"#2 c #945a5a",
"#H c #9c5252",
"#G c #9c5a52",
"#1 c #9c6b6b",
"#0 c #9c7373",
"#A c #a55252",
"#E c #a55a52",
"#L c #a55a5a",
"#V c #a57373",
".c c #ad5252",
"#z c #ad5a52",
".m c #ad5a5a",
"#D c #ad6352",
"#T c #ad6b6b",
"#F c #ad7373",
"#Z c #ad8484",
".k c #b55252",
".z c #b55a52",
"#x c #b56352",
".y c #b56b6b",
".f c #b57373",
"#Y c #b58c8c",
"#W c #b59494",
".x c #bd5252",
".g c #bd5a52",
"#w c #bd6352",
".b c #bd8484",
".S c #bd8c8c",
"#I c #bd9494",
".h c #c65a52",
"#u c #c66352",
".e c #c69494",
".d c #c6a5a5",
"#3 c #c6b5b5",
".i c #ce5a52",
".G c #ce6352",
".a c #ceb5b5",
".l c #cec6c6",
".w c #d65a52",
".j c #d66352",
".n c #d6635a",
"#R c #d66b5a",
"#N c #d67363",
".# c #d6c6c6",
".0 c #d6cece",
"Qt c #d9d9d9",
".Z c #de5a52",
"#k c #de6352",
"#J c #de6b5a",
"#y c #de7363",
"#O c #de7b73",
"#C c #de8473",
".R c #e75a52",
".7 c #e76352",
".T c #e7635a",
".H c #e76b5a",
"#s c #e77363",
"#v c #e78473",
".v c #ef6352",
"#b c #ef635a",
".o c #ef6b5a",
"#q c #ef8473",
"#f c #ef8c84",
"#n c #ef9484",
"#S c #efa59c",
"#B c #efbdb5",
".u c #f76352",
".p c #f76b5a",
".5 c #f7735a",
".q c #f77363",
"#j c #f78c7b",
"#e c #f79484",
"#Q c #f79c8c",
"#l c #f79c94",
"## c #f7a594",
"#M c #f7b5ad",
"#h c #f7bdad",
"#p c #f7c6bd",
"#t c #f7cec6",
"#r c #f7d6d6",
".F c #ff6352",
"#i c #ff6b52",
".t c #ff6b5a",
".s c #ff735a",
".r c #ff7363",
".I c #ff7b63",
".A c #ff7b6b",
".1 c #ff846b",
".B c #ff8473",
".Y c #ff8c73",
".C c #ff8c7b",
".D c #ff947b",
".E c #ff9484",
".J c #ff9c8c",
".8 c #ffa58c",
".Q c #ffa594",
".K c #ffa59c",
".P c #ffad9c",
".L c #ffada5",
".M c #ffb5a5",
".O c #ffb5ad",
".N c #ffbdad",
".X c #ffbdb5",
".U c #ffc6b5",
".W c #ffc6bd",
".4 c #ffcebd",
".V c #ffcec6",
".3 c #ffd6c6",
".2 c #ffd6ce",
"#c c #ffd6d6",
".6 c #ffded6",
".9 c #ffdede",
"#m c #ffe7de",
"#d c #ffefe7",
"#a c #ffefef",
"#o c #fff7ef",
"#g c #fff7f7",
"#. c #ffffff",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.a.a.b.c.c.c.c.c.c.c.c.b.a.a.#QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.d.e.f.c.c.g.h.i.i.j.j.i.i.h.k.c.c.f.e.dQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt.l.f.m.c.g.n.o.o.p.q.r.r.s.t.p.u.v.v.w.x.c.m.f.lQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.#.y.c.z.i.o.r.A.B.C.D.E.E.E.D.C.B.A.r.s.t.F.v.h.k.c.y.#QtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.e.f.c.G.H.I.B.D.J.K.L.M.N.O.O.M.P.Q.J.D.B.I.s.t.F.R.i.c.f.eQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.S.c.z.T.q.B.E.P.O.U.V.V.V.V.W.W.X.N.M.P.Q.E.Y.A.r.t.F.u.Z.k.c.SQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQt.0.b.c.h.o.1.E.P.X.V.2.2.3.4.U.O.L.P.Q.Q.J.J.J.E.C.B.I.t.t.u.u.v.h.c.b.0QtQtQtQtQtQt",
"QtQtQtQtQtQt.b.c.h.q.B.J.O.V.2.2.3.W.O.P.J.E.C.Y.1.1.1.1.1.1.1.1.I.t.p.u.u.u.v.h.c.bQtQtQtQtQtQt",
"QtQtQtQtQt.S.c.h.5.Y.Q.N.2.6.2.W.M.Q.D.B.A.r.r.s.t.t.t.t.t.s.s.s.s.t.p.u.u.u.u.7.h.c.SQtQtQtQtQt",
"QtQtQtQt.e.c.h.q.B.Q.U.2.2.4.O.J.C.A.r.t.t.F.F.F.F.F.F.F.F.F.F.F.u.u.u.u.u.u.v.v.7.h.c.eQtQtQtQt",
"QtQtQt.#.f.z.o.B.8.U.2.2.U.P.E.1.r.t.F.F.F.F.F.F.F.F.F.F.F.F.u.u.u.u.u.u.u.v.v.v.v.7.k.f.#QtQtQt",
"QtQtQt.y.c.T.A.J.N.2.2.U.Q.C.1.D.s.F.F.F.F.F.F.F.F.F.F.F.F.F.u.u.q.q.u.u.v.v.v.v.v.v.w.c.yQtQtQt",
"QtQt.l.c.i.q.D.M.V.V.N.J.B.C.9#..2.1.F.F.F.F.F.F.F.F.F.F.u.u.p###a#a###b.v.v.v.v.v.7.7.h.c.lQtQt",
"QtQt.f.z.H.1.Q.U.V.N.J.B.C#c#.#.#..2.r.F.F.F.F.F.F.F.F.u.u.u###d#.#.#d##.v.v.v.v.7.7.7.j.k.fQtQt",
"Qt.d.m.i.r.C.M.W.U.Q.B.r.6#.#.#.#.#..V.r.F.F.F.F.F.F.u.u.u#e#a#.#.#.#.#a#f.v.7.7.7.7.7.7.g.m.dQt",
"Qt.e.c#b.A.J.N.X.P.B.r.A#g#.#.#.#.#.#..2.1.F.F.F.u.u.u.p###a#.#.#.#.#.#.#h.7.7.7.7.7.7.7.j.c.eQt",
".#.f.g.s.B.Q.N.L.E.r.t#i.W#g#.#.#.#.#.#..2.r.F.F.u.u.u###d#.#.#.#.#.#.#a#j.7.7.7.7.7.7#k#k.k.f.#",
".a.c.j.r.D.P.M.J.1.t.F.F.r.W#g#.#.#.#.#.#..V.r.u.u.u#e#a#.#.#.#.#.#.#a#l.7.7.7.7.7.7#k#k#k.h.c.a",
".a.c#b.I.E.P.Q.C.r.F.F.F.F.t.X#g#.#.#.#.#.#..2.A.p###a#.#.#.#.#.#.#m#n.7.7.7.7.7.7#k#k#k#k.G.c.a",
".b.k#b.1.E.Q.E.A.t.F.F.F.F.F.t.W#g#.#.#.#.#.#..2.P#d#.#.#.#.#.#.#a#n.7.7.7.7.7.7#k#k#k#k#k.j.k.b",
".c.h.p.1.E.J.Y.r.t.F.F.F.F.F.F.r.W#g#.#.#.#.#.#.#o#.#.#.#.#.#.#a#l.7.7.7.7.7.7#k#k#k#k#k#k.j.z.c",
".c.i.p.A.C.C.A.t.F.F.F.F.F.F.F.F.t.X#g#.#.#.#.#.#.#.#.#.#.#.#m#n.7.7.7.7.7#k#k#k#k#k#k.j.j.j.g.c",
".c.i.t.I.B.B.r.t.F.F.F.F.F.F.F.F.F.p.W#g#.#.#.#.#.#.#.#.#.#a#n.7.7.7.7.7#k#k#k#k#k#k.j.j.j.j.g.c",
".c.w.t.r.A.I.t.F.F.F.F.F.F.F.F.F.u.u.q#p#g#.#.#.#.#.#.#.#a#l.7.7.7.7.7#k#k#k#k#k#k#k.j.j.j.j.g.c",
".c.w.F.t.r.s.t.F.F.F.F.F.F.F.u.u.u.u.p.K#a#.#.#.#.#.#.#.#c#q.7.7.7.7#k#k#k#k#k#k.j.j.j.j.G.G.g.c",
".c.i.F.t.t.t.F.F.F.F.F.F.F.u.u.u.u.u###d#.#.#.#.#.#.#.#.#.#r#s.7.7#k#k#k#k#k#k.j.j.j.j.G.G.G.g.c",
".c.h.u.F.F.F.F.F.F.F.F.F.u.u.u.u.u#e#a#.#.#.#.#.#.#.#.#.#.#.#t#s#k#k#k#k#k#k.j.j.j.j.G.G#u#u.z.c",
".c.h.u.F.F.F.F.F.F.F.F.u.u.u.u.p###a#.#.#.#.#.#.#.#.#.#.#.#.#.#r#v#k#k#k.j.j.j.j.j.j.G#u#w#w.c.c",
".b.k.v.F.F.F.F.F.F.F.u.u.u.u.u###d#.#.#.#.#.#.#a#t#g#.#.#.#.#.#.#r#s#k#k.j.j.j.j.j.G#u#w#x.z.c.b",
".a.c.v.F.F.F.F.F.F.u.u.u.u.u#e#a#.#.#.#.#.#.#a#l#s#p#g#.#.#.#.#.#.#t#y.j.j.j.j.j.j.G#u#w#x#z#A.a",
".a.c.w.F.F.F.F.u.u.u.u.u.p###a#.#.#.#.#.#.#m#n.7.7.H#B#g#.#.#.#.#.#.#r#C.j.j.j.j.G#u#w#D#D#E#A.a",
".#.f.x.F.F.F.u.u.u.u.u.u###d#.#.#.#.#.#.#a#n.7.7.7.7.H#p#g#.#.#.#.#.#.#r#y.j.j.G.G#u#x#D#E#A#F.l",
"Qt.e.c.v.F.u.u.u.u.u.u.q#a#.#.#.#.#.#.#a#l.7.7.7.7#k#k#s#p#g#.#.#.#.#.#.#B.j.G.G#u#w#D#E#G#H#IQt",
"Qt.d.m.h.u.u.u.u.u.u.v.q#g#.#.#.#.#.#m#n.7.7.7#k#k#k#k#k#J#B#g#.#.#.#.#.#B.G.G#u#w#x#E#G#K#L.dQt",
"QtQt.f.k.R.u.u.u.u.v.v.v#M#o#.#.#.#a#n.7.7.7#k#k#k#k#k#k#k#J#p#g#.#.#.#r#N.G.G#u#x#E#G#G#K#FQtQt",
"QtQt.l.c.i.v.u.u.v.v.v.v.o#M#g#.#a#l.7.7.7#k#k#k#k#k#k.j.j.j#y#p#g#.#r#O.G.G#u#w#D#G#P#P#K.lQtQt",
"QtQtQt.y.c.w.v.v.v.v.v.v.v.7#Q#t#f.7.7.7#k#k#k#k#k#k.j.j.j.j.j#R#S#S#N.G.G#u#w#D#G#P#P#K#TQtQtQt",
"QtQtQt.#.f.k.7.v.v.v.v.v.7.7.7.7.7.7.7#k#k#k#k#k#k.j.j.j.j.j.j.j.G.G.G.G#u#w#D#G#P#P#U#V.lQtQtQt",
"QtQtQtQt.e.c.h.7.v.v.v.7.7.7.7.7.7#k#k#k#k#k#k#k.j.j.j.j.j.j.j.G.G.G.G#u#w#D#E#P#P#U#K#WQtQtQtQt",
"QtQtQtQtQt.S.c.g.7.v.7.7.7.7.7.7#k#k#k#k#k#k.j.j.j.j.j.j.j.j.G.G.G#u#u#x#D#G#P#X#X#U#YQtQtQtQtQt",
"QtQtQtQtQtQt.b.c.g.7.7.7.7.7.7#k#k#k#k#k#k.j.j.j.j.j.j.j.G.G.G.G#u#w#x#D#G#P#X#X#U#ZQtQtQtQtQtQt",
"QtQtQtQtQtQt.0.b.c.h#k.7.7.7#k#k#k#k#k.j.j.j.j.j.j.j.G.G.G#u#u#w#x#D#E#G#P#X#U#U#Z.0QtQtQtQtQtQt",
"QtQtQtQtQtQtQtQt.S.c.k.i#k#k#k.j.j.G.G.G.G.G.G.G.G.G#u#u#w#w#x#D#E#G#P#X#X#U#U#YQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQt.e.f.c.h.i.j.j.G#u#u#u#u#w#w#w#w#w#x#x#D#E#E#G#P#X#X#U#U#0#WQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQt.#.y.c.c.g.G.G#u#w#x#x#D#D#D#D#E#E#E#G#G#P#P#X#U#U#U#1.lQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQt.l.f.m#A.c.z.z.z#z#E#E#E#G#G#P#P#P#X#X#U#U#2#V.lQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQt.d#I.f#A#A#A#A#G#G#G#P#P#P#U#U#U#U#V#W.dQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.a.a.b#A#H#H#H#K#K#K#K#Z#3#3.lQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt"};

static const char* const img7_gemdDlg[] = { 
"64 32 6 1",
"c c #000000",
"b c #d9d9d9",
"d c #f77363",
". c #ff63ff",
"# c #ff6bb5",
"a c #ff7363",
".##aaa##bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"#aaaaaaaa#bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"aaaaaaaaaaa#bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"baaaaaaaaaaaa#bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb##aa#bbbbbbb",
"bb#aaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb#aaaaa#bbbbbbb",
"bbbb#aaaaaaaaaaa#bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb#aaaaa#bbbbbbbbb",
"bbbbbb#aacccccaaaa#bbbbbbbbbbbbbbbbbbccbbbbbb##aaaaa#bcbbbbbbbbb",
"bbbbbbbb#ccaaccaaaaa#bbbbbbbbbbbbbbbbccbbbb#aaaaaa#bbccbbbbbbbbb",
"bbbbbbbbbccaaccaacccca#bccccbbbccccbbccbbccccaaacccbccccbbbbbbbb",
"bbbbbbbbbccb#ccaccaaccaccbbccbccbbccbccaccaacc#ccbccbccbbbbbbbbb",
"bbbbbbbbbccbbccaccccccaccccbbbcccccc#ccaccccccbccbbbbccbbbbbbbbb",
"bbbbbbbbbccbbccbccaaaaaaaccccbccbb#aaccacc#bbbbccbbbbccbbbbbbbbb",
"bbbbbbbbbccbbccbcc#accaccaacc#ccaaccaccaccbbccbccbccbccbbbbbbbbb",
"bbbbbbbbbcccccbbbccccaaaccccaaaccccaaccbbccccbbbcccbbbccbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbb#aaaaaaaaaaaaa#bbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaa#bbbbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbb#aaaaaaaaaaaaaa#bbbbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbb#aaaaaaaaaaaaaadddd#bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbb#aaaaaaaaaa#b#adddddddddbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbb#aaaaaaaaaa#bbbbb#ddddddddd#bbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbb#aaaaaaaaaa#bbbbbbbbccdccdddddd#bbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbb#aaaaaaaaaaa#bbbbbbbbbbccbccdddddddd#bbbbbbbbbbbbbbbbb",
"bbbbbbbb#aaaaaaaaaaa#bbbbbbbcccbbccbcc#ddddddddd#bbbbbbbbbbbbbbb",
"bbbbbb#aaaaaaaaaaa#bbbbbbbbcbbccbccbccbb#ddddddddd#bbbbbbbbbbbbb",
"bbb#aaaaaaaaaaaa#bbbbbbbbbbbccccbccbccbbbb#ddddddddd#bbbbbbbbbbb",
"bbaaaaaaaaaaaa#bbbbbbbbbbbbccbccbccbccbbbbbb#dddddddddbbbbbbbbbb",
"bbaaaaaaaaaa#bbbbbbbbbbbbbbccbccbccbccbbbbbbbb#dddddddd#bbbbbbbb",
"bb#aaaaaaa#bbbbbbbbbbbbbbbbbccccbccbccbbbbbbbbbb#dddddddd#bbbbbb",
"bbbb#####bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb#dddddddd#bbbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb#dddddddd#bb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb#dddddddbb",
"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb#dddd#bb"};


/*
 *  Constructs a gemdBase as a child of 'parent', with the
 *  name 'name' and widget flags set to 'f'.
 *
 *  The dialog will by default be modeless, unless you set 'modal' to
 *  TRUE to construct a modal dialog.
 */
gemdBase::gemdBase( QWidget* parent, const char* name, bool modal, WFlags fl )
    : QDialog( parent, name, modal, fl ),
      image0( (const char **) img0_gemdDlg ),
      image1( (const char **) img1_gemdDlg ),
      image2( (const char **) img2_gemdDlg ),
      image3( (const char **) img3_gemdDlg ),
      image4( (const char **) img4_gemdDlg ),
      image5( (const char **) img5_gemdDlg ),
      image6( (const char **) img6_gemdDlg ),
      image7( (const char **) img7_gemdDlg )
{
    if ( !name )
	setName( "gemdBase" );
    setMinimumSize( QSize( 500, 452 ) );
    setMaximumSize( QSize( 500, 452 ) );
    setPaletteBackgroundColor( QColor( 217, 217, 217 ) );

    addfP = new QTextEdit( this, "addfP" );
    addfP->setGeometry( QRect( 300, 310, 64, 64 ) );
    addfP->setMinimumSize( QSize( 64, 64 ) );
    addfP->setMaximumSize( QSize( 64, 64 ) );
    addfP->setPaletteBackgroundPixmap( image0 );
    addfP->setLineWidth( 0 );
    addfP->setReadOnly( TRUE );
    addfP->setUndoRedoEnabled( FALSE );
    addfP->setTabStopWidth( 0 );

    opdirP = new QTextEdit( this, "opdirP" );
    opdirP->setGeometry( QRect( 300, 150, 64, 64 ) );
    opdirP->setMinimumSize( QSize( 64, 64 ) );
    opdirP->setMaximumSize( QSize( 64, 64 ) );
    opdirP->setPaletteBackgroundPixmap( image1 );
    opdirP->setLineWidth( 0 );
    opdirP->setReadOnly( TRUE );
    opdirP->setUndoRedoEnabled( FALSE );
    opdirP->setTabStopWidth( 0 );

    dirupP = new QTextEdit( this, "dirupP" );
    dirupP->setGeometry( QRect( 410, 150, 64, 64 ) );
    dirupP->setMinimumSize( QSize( 64, 64 ) );
    dirupP->setMaximumSize( QSize( 64, 64 ) );
    dirupP->setPaletteBackgroundPixmap( image2 );
    dirupP->setLineWidth( 0 );
    dirupP->setReadOnly( TRUE );
    dirupP->setUndoRedoEnabled( FALSE );
    dirupP->setTabStopWidth( 0 );

    setddP = new QTextEdit( this, "setddP" );
    setddP->setGeometry( QRect( 410, 220, 64, 64 ) );
    setddP->setMinimumSize( QSize( 64, 64 ) );
    setddP->setMaximumSize( QSize( 64, 64 ) );
    setddP->setPaletteBackgroundPixmap( image3 );
    setddP->setLineWidth( 0 );
    setddP->setReadOnly( TRUE );
    setddP->setUndoRedoEnabled( FALSE );
    setddP->setTabStopWidth( 0 );

    extrP = new QTextEdit( this, "extrP" );
    extrP->setGeometry( QRect( 300, 220, 64, 64 ) );
    extrP->setMinimumSize( QSize( 64, 64 ) );
    extrP->setMaximumSize( QSize( 64, 64 ) );
    extrP->setPaletteBackgroundPixmap( image4 );
    extrP->setLineWidth( 0 );
    extrP->setReadOnly( TRUE );
    extrP->setUndoRedoEnabled( FALSE );
    extrP->setTabStopWidth( 0 );

    newfP = new QTextEdit( this, "newfP" );
    newfP->setGeometry( QRect( 400, 310, 64, 64 ) );
    newfP->setMinimumSize( QSize( 64, 64 ) );
    newfP->setMaximumSize( QSize( 64, 64 ) );
    newfP->setPaletteBackgroundPixmap( image5 );
    newfP->setLineWidth( 0 );
    newfP->setReadOnly( TRUE );
    newfP->setUndoRedoEnabled( FALSE );
    newfP->setTabStopWidth( 0 );

    errti = new QLabel( this, "errti" );
    errti->setGeometry( QRect( 400, 290, 71, 17 ) );

    quitP = new QTextEdit( this, "quitP" );
    quitP->setGeometry( QRect( 450, 400, 48, 48 ) );
    quitP->setMinimumSize( QSize( 48, 48 ) );
    quitP->setMaximumSize( QSize( 48, 48 ) );
    quitP->setPaletteBackgroundPixmap( image6 );
    quitP->setLineWidth( 0 );
    quitP->setReadOnly( TRUE );
    quitP->setUndoRedoEnabled( FALSE );
    quitP->setTabStopWidth( 0 );

    textLabel1 = new QLabel( this, "textLabel1" );
    textLabel1->setGeometry( QRect( 250, 380, 86, 20 ) );

    dirED = new QLineEdit( this, "dirED" );
    dirED->setGeometry( QRect( 340, 380, 110, 21 ) );
    dirED->setLineWidth( 0 );
    dirED->setMaxLength( 12 );
    dirED->setFrame( FALSE );

    exwht = new QLabel( this, "exwht" );
    exwht->setGeometry( QRect( 260, 290, 120, 20 ) );

    desallP = new QTextEdit( this, "desallP" );
    desallP->setGeometry( QRect( 270, 410, 64, 32 ) );
    desallP->setMinimumSize( QSize( 64, 32 ) );
    desallP->setMaximumSize( QSize( 64, 32 ) );
    desallP->setPaletteBackgroundPixmap( image7 );
    desallP->setLineWidth( 0 );
    desallP->setReadOnly( TRUE );
    desallP->setUndoRedoEnabled( FALSE );
    desallP->setTabStopWidth( 0 );

    textLabel1_2 = new QLabel( this, "textLabel1_2" );
    textLabel1_2->setGeometry( QRect( 341, 430, 100, 20 ) );

    timeCB = new QCheckBox( this, "timeCB" );
    timeCB->setGeometry( QRect( 340, 410, 100, 20 ) );

    partsBut = new QPushButton( this, "partsBut" );
    partsBut->setGeometry( QRect( 330, 0, 90, 20 ) );
    partsBut->setFlat( TRUE );

    partLB = new QListBox( this, "partLB" );
    partLB->setGeometry( QRect( 270, 20, 211, 111 ) );

    dirLabel = new QLabel( this, "dirLabel" );
    dirLabel->setGeometry( QRect( 0, 0, 240, 17 ) );
    dirLabel->setAlignment( int( QLabel::AlignVCenter | QLabel::AlignRight ) );

    filesLB = new QListBox( this, "filesLB" );
    filesLB->setGeometry( QRect( 0, 20, 250, 400 ) );
    QFont filesLB_font(  filesLB->font() );
    filesLB_font.setFamily( "Fixed [Misc]" );
    filesLB_font.setPointSize( 12 );
    filesLB_font.setBold( TRUE );
    filesLB->setFont( filesLB_font ); 
    filesLB->setSelectionMode( QListBox::Multi );

    usfrLabel = new QLabel( this, "usfrLabel" );
    usfrLabel->setGeometry( QRect( 20, 430, 211, 20 ) );

    partinfLab = new QLabel( this, "partinfLab" );
    partinfLab->setGeometry( QRect( 271, 130, 210, 20 ) );
    languageChange();
    resize( QSize(500, 452).expandedTo(minimumSizeHint()) );
    clearWState( WState_Polished );

    // signals and slots connections
    connect( partLB, SIGNAL( clicked(QListBoxItem*) ), this, SLOT( partLB_clicked(QListBoxItem*) ) );
    connect( filesLB, SIGNAL( clicked(QListBoxItem*) ), this, SLOT( filesLB_clicked(QListBoxItem*) ) );
    connect( dirupP, SIGNAL( clicked(int,int) ), this, SLOT( dirupP_clicked(int,int) ) );
    connect( opdirP, SIGNAL( clicked(int,int) ), this, SLOT( opdirP_clicked(int,int) ) );
    connect( extrP, SIGNAL( clicked(int,int) ), this, SLOT( extrP_clicked(int,int) ) );
    connect( setddP, SIGNAL( clicked(int,int) ), this, SLOT( setddP_clicked(int,int) ) );
    connect( addfP, SIGNAL( clicked(int,int) ), this, SLOT( addfP_clicked(int,int) ) );
    connect( newfP, SIGNAL( clicked(int,int) ), this, SLOT( newfP_clicked(int,int) ) );
    connect( quitP, SIGNAL( clicked(int,int) ), this, SLOT( quitP_clicked(int,int) ) );
    connect( desallP, SIGNAL( clicked(int,int) ), this, SLOT( desallP_clicked(int,int) ) );
    connect( filesLB, SIGNAL( doubleClicked(QListBoxItem*) ), this, SLOT( filesLB_doubleClicked(QListBoxItem*) ) );
    connect( timeCB, SIGNAL( clicked() ), this, SLOT( timeCB_clicked() ) );
    connect( partsBut, SIGNAL( clicked() ), this, SLOT( partsBut_clicked() ) );
}

/*
 *  Destroys the object and frees any allocated resources
 */
gemdBase::~gemdBase()
{
    // no need to delete child widgets, Qt does it all for us
}

/*
 *  Sets the strings of the subwidgets using the current
 *  language.
 */
void gemdBase::languageChange()
{
    setCaption( tr2i18n( "GemDOS file browser & transfer" ) );
    errti->setText( QString::null );
    textLabel1->setText( tr2i18n( "Folder name:" ) );
    exwht->setText( QString::null );
    textLabel1_2->setText( tr2i18n( "else filetime st." ) );
    timeCB->setText( tr2i18n( "Curre&nt time" ) );
    timeCB->setAccel( QKeySequence( tr2i18n( "Alt+N" ) ) );
    partsBut->setText( tr2i18n( "Partiti&ons:" ) );
    partsBut->setAccel( QKeySequence( tr2i18n( "Alt+O" ) ) );
    dirLabel->setText( tr2i18n( "Dir" ) );
    usfrLabel->setText( QString::null );
    partinfLab->setText( QString::null );
}

void gemdBase::partLB_clicked(QListBoxItem*)
{
    qWarning( "gemdBase::partLB_clicked(QListBoxItem*): Not implemented yet" );
}

void gemdBase::filesLB_clicked(QListBoxItem*)
{
    qWarning( "gemdBase::filesLB_clicked(QListBoxItem*): Not implemented yet" );
}

void gemdBase::dirupP_clicked(int,int)
{
    qWarning( "gemdBase::dirupP_clicked(int,int): Not implemented yet" );
}

void gemdBase::opdirP_clicked(int,int)
{
    qWarning( "gemdBase::opdirP_clicked(int,int): Not implemented yet" );
}

void gemdBase::extrP_clicked(int,int)
{
    qWarning( "gemdBase::extrP_clicked(int,int): Not implemented yet" );
}

void gemdBase::setddP_clicked(int,int)
{
    qWarning( "gemdBase::setddP_clicked(int,int): Not implemented yet" );
}

void gemdBase::addfP_clicked(int,int)
{
    qWarning( "gemdBase::addfP_clicked(int,int): Not implemented yet" );
}

void gemdBase::newfP_clicked(int,int)
{
    qWarning( "gemdBase::newfP_clicked(int,int): Not implemented yet" );
}

void gemdBase::quitP_clicked(int,int)
{
    qWarning( "gemdBase::quitP_clicked(int,int): Not implemented yet" );
}

void gemdBase::desallP_clicked(int,int)
{
    qWarning( "gemdBase::desallP_clicked(int,int): Not implemented yet" );
}

void gemdBase::filesLB_doubleClicked(QListBoxItem*)
{
    qWarning( "gemdBase::filesLB_doubleClicked(QListBoxItem*): Not implemented yet" );
}

void gemdBase::timeCB_clicked()
{
    qWarning( "gemdBase::timeCB_clicked(): Not implemented yet" );
}

void gemdBase::partsBut_clicked()
{
    qWarning( "gemdBase::partsBut_clicked(): Not implemented yet" );
}

#include "gemdDlg.moc"
